"""
Base de données RÉALISTE des modèles de business rentables.
Fourchettes conservatrices, pas de hype.

=== OBJECTIFS NET EN SAS ===
- Objectif 1: 5 000€ NET/mois (en poche après charges)
- Objectif 2: 8 000€ NET/mois (5k vous + 3k assistant)

=== CALCUL NET SAS ===
Pour 5k€ NET en SAS (mix salaire+dividendes optimal):
- CA nécessaire: ~8 500 - 10 000€/mois
- Charges sociales président: ~45% du salaire brut
- Flat tax dividendes: 30%
- IS sur bénéfices: 25%

Les revenus affichés sont en CA (chiffre d'affaires).
Le champ "ca_objectif_5k_net" indique le CA mensuel nécessaire pour 5k€ NET.

=== MISE À JOUR 2026 ===
- Ajout business IA/Automatisation (forte demande)
- Revenus corrigés CA vs NET
- Tendances 2026 actualisées
"""

BUSINESS_MODELS = {
    # ============================================================
    # FREELANCE / SERVICES INDIVIDUELS
    # Ces business sont les plus réalistes pour atteindre 5k rapidement
    # ============================================================
    "freelance_dev": {
        "nom": "Développeur Freelance",
        "categorie": "Freelance",
        "description": "Prestations de développement web/mobile pour des clients",
        "revenus_potentiels": "4 000 - 12 000€ CA/mois",
        "revenus_median": "6 500€ CA/mois",
        "ca_objectif_5k_net": "8 500€ CA/mois",  # Pour 5k€ NET en SAS
        "temps_objectif_5k": "4-10 mois",  # Pour atteindre 8.5k CA = 5k NET
        "capital_requis": "0 - 500€",
        "scalabilite": 2,
        "realisme": 5,  # 1-5, 5 = très réaliste
        "competences_requises": ["Développement web/mobile"],
        "competences_bonus": ["Gestion de projet", "Vente/Négociation"],
        "modele_revenu": "Prestations de service (freelance, consulting)",
        "type_client": "B2B - Entreprises/Professionnels",
        "lieu": ["100% à domicile/remote", "Nomade digital - depuis n'importe où"],
        "visibilite": ["Modérément - je préfère rester en retrait", "Non - je veux un business anonyme/discret"],
        "risque": 1,
        "avantages": ["Démarrage rapide", "Forte demande", "TJM 400-600€ réaliste senior"],
        "inconvenients": ["Échange temps/argent", "Prospection continue", "Isolement"],
        "etapes_demarrage": ["Portfolio GitHub solide", "Malt + LinkedIn actif", "3 premiers clients via réseau", "TJM progressif"],
        "ressources": ["Malt.fr", "Comet.co", "LinkedIn"],
        "warning": "TJM 400€ x 17j = 6.8k CA → ~4k NET. Visez 500€+ pour 5k NET"
    },
    "freelance_design": {
        "nom": "Designer Freelance (UI/UX/Graphique)",
        "categorie": "Freelance",
        "description": "Création de designs, interfaces, identités visuelles",
        "revenus_potentiels": "2 500 - 6 000€/mois",
        "revenus_median": "3 500€/mois",
        "temps_objectif_5k": "6-12 mois",
        "capital_requis": "500 - 1 500€",
        "scalabilite": 2,
        "realisme": 4,
        "competences_requises": ["Design graphique/UI-UX"],
        "competences_bonus": ["Marketing digital/SEO/Ads"],
        "modele_revenu": "Prestations de service (freelance, consulting)",
        "type_client": "B2B - Entreprises/Professionnels",
        "lieu": ["100% à domicile/remote", "Nomade digital - depuis n'importe où"],
        "visibilite": ["Modérément - je préfère rester en retrait"],
        "risque": 1,
        "avantages": ["Portfolio visuel", "Créativité valorisée"],
        "inconvenients": ["Subjectivité clients", "Révisions nombreuses", "Concurrence internationale"],
        "etapes_demarrage": ["Portfolio Behance 10+ projets", "Spécialisation niche", "Malt/Dribbble", "Réseau agences"],
        "ressources": ["Behance", "Dribbble", "Figma"],
        "warning": "Marché plus concurrentiel que le dev, spécialisez-vous"
    },
    "freelance_marketing": {
        "nom": "Consultant Marketing Digital",
        "categorie": "Freelance",
        "description": "Accompagnement en marketing digital, SEO, publicités",
        "revenus_potentiels": "4 000 - 10 000€ CA/mois",
        "revenus_median": "6 000€ CA/mois",
        "ca_objectif_5k_net": "8 500€ CA/mois",
        "temps_objectif_5k": "5-12 mois",
        "capital_requis": "0 - 1 000€",
        "scalabilite": 3,
        "realisme": 5,
        "competences_requises": ["Marketing digital/SEO/Ads"],
        "competences_bonus": ["Rédaction/Copywriting", "Vente/Négociation"],
        "modele_revenu": "Prestations de service (freelance, consulting)",
        "type_client": "B2B - Entreprises/Professionnels",
        "lieu": ["100% à domicile/remote", "Nomade digital - depuis n'importe où"],
        "visibilite": ["Oui, je veux être le visage de mon business", "Oui, mais uniquement sur certains canaux"],
        "risque": 1,
        "avantages": ["Forte demande PME", "Résultats mesurables", "Récurrence possible (forfaits 1-2k/mois)"],
        "inconvenients": ["Devoir prouver ROI", "Clients exigeants", "Veille constante"],
        "etapes_demarrage": ["Certifications Google/Meta", "3 études de cas réelles", "Prospection LinkedIn", "Forfaits mensuels 1500-3000€"],
        "ressources": ["Google Skillshop", "HubSpot Academy", "Semrush"],
        "warning": "4-5 clients à 2k€/mois = 8-10k CA → 5k NET réaliste"
    },
    "freelance_copywriter": {
        "nom": "Copywriter/Rédacteur Web",
        "categorie": "Freelance",
        "description": "Rédaction persuasive, pages de vente, emails, contenus SEO",
        "revenus_potentiels": "2 000 - 5 000€/mois",
        "revenus_median": "3 000€/mois",
        "temps_objectif_5k": "8-15 mois",
        "capital_requis": "0 - 300€",
        "scalabilite": 2,
        "realisme": 4,
        "competences_requises": ["Rédaction/Copywriting"],
        "competences_bonus": ["Marketing digital/SEO/Ads"],
        "modele_revenu": "Prestations de service (freelance, consulting)",
        "type_client": "B2B - Entreprises/Professionnels",
        "lieu": ["100% à domicile/remote", "Nomade digital - depuis n'importe où"],
        "visibilite": ["Non - je veux un business anonyme/discret", "Modérément - je préfère rester en retrait"],
        "risque": 1,
        "avantages": ["Zéro investissement", "Travail partout", "Niche pages de vente lucrative"],
        "inconvenients": ["Tarifs bas au début (0.10€/mot)", "Volume important", "Deadlines serrées"],
        "etapes_demarrage": ["Portfolio 5-10 textes", "Spécialisation (B2B, e-commerce, santé)", "Malt + cold email", "Augmenter tarifs progressivement"],
        "ressources": ["Redacteur.com", "Malt", "Scribeur"],
        "warning": "⚠️ 2026: IA impacte fortement ce métier. Spécialisez-vous en stratégie/voix de marque, pas en volume."
    },
    "freelance_video": {
        "nom": "Monteur Vidéo/Motion Designer",
        "categorie": "Freelance",
        "description": "Montage vidéo, motion design pour entreprises et créateurs",
        "revenus_potentiels": "2 500 - 6 000€/mois",
        "revenus_median": "3 500€/mois",
        "temps_objectif_5k": "6-12 mois",
        "capital_requis": "1 500 - 4 000€",
        "scalabilite": 2,
        "realisme": 4,
        "competences_requises": ["Vidéo/Montage"],
        "competences_bonus": ["Design graphique/UI-UX", "Créativité/Innovation"],
        "modele_revenu": "Prestations de service (freelance, consulting)",
        "type_client": "Les deux me conviennent",
        "lieu": ["100% à domicile/remote", "Nomade digital - depuis n'importe où"],
        "visibilite": ["Non - je veux un business anonyme/discret"],
        "risque": 1,
        "avantages": ["Demande croissante", "Tarifs corrects motion", "Clients récurrents possibles"],
        "inconvenients": ["PC puissant obligatoire", "Fichiers lourds", "Révisions chronophages"],
        "etapes_demarrage": ["Showreel 2 min", "Cibler agences ou créateurs", "Tarif au projet", "Clients récurrents"],
        "ressources": ["Premiere Pro", "After Effects", "DaVinci Resolve"],
        "warning": "Investissement matériel conséquent (PC + logiciels)"
    },
    "freelance_comptable": {
        "nom": "Comptable/Gestionnaire Indépendant",
        "categorie": "Freelance",
        "description": "Services comptables pour TPE et indépendants",
        "revenus_potentiels": "3 500 - 7 000€/mois",
        "revenus_median": "4 500€/mois",
        "temps_objectif_5k": "4-8 mois",
        "capital_requis": "1 000 - 3 000€",
        "scalabilite": 3,
        "realisme": 5,
        "competences_requises": ["Comptabilité/Finance"],
        "competences_bonus": ["Vente/Négociation", "Organisation/Rigueur"],
        "modele_revenu": "Prestations de service (freelance, consulting)",
        "type_client": "B2B - Entreprises/Professionnels",
        "lieu": ["100% à domicile/remote", "Principalement à domicile avec déplacements occasionnels"],
        "visibilite": ["Modérément - je préfère rester en retrait"],
        "risque": 1,
        "avantages": ["Récurrence assurée", "Clients fidèles 5+ ans", "Demande constante"],
        "inconvenients": ["Pics janvier/mai", "Responsabilité", "Diplôme souvent attendu"],
        "etapes_demarrage": ["Logiciel comptable", "Cibler freelances tech", "Forfaits clairs 150-400€/mois", "Bouche-à-oreille"],
        "ressources": ["Pennylane", "Indy", "QuickBooks"],
        "warning": "Sans diplôme, limitez-vous à la gestion (pas d'expertise-comptable)"
    },

    # ============================================================
    # AGENCES
    # Scalable mais demande gestion d'équipe
    # ============================================================
    "agence_seo": {
        "nom": "Agence SEO",
        "categorie": "Agence",
        "description": "Services de référencement naturel pour entreprises",
        "revenus_potentiels": "5 000 - 15 000€/mois",
        "revenus_median": "7 000€/mois",
        "temps_objectif_5k": "6-12 mois",
        "capital_requis": "1 000 - 5 000€",
        "scalabilite": 4,
        "realisme": 4,
        "competences_requises": ["Marketing digital/SEO/Ads"],
        "competences_bonus": ["Rédaction/Copywriting", "Développement web/mobile"],
        "modele_revenu": "Prestations de service (freelance, consulting)",
        "type_client": "B2B - Entreprises/Professionnels",
        "lieu": ["100% à domicile/remote"],
        "visibilite": ["Oui, mais uniquement sur certains canaux"],
        "risque": 2,
        "avantages": ["Revenus très récurrents (12-24 mois)", "Résultats mesurables", "Scalable"],
        "inconvenients": ["Résultats longs (3-6 mois)", "Google change les règles", "Éducation client"],
        "etapes_demarrage": ["Outils SEO (Ahrefs/Semrush)", "3 études de cas", "Forfaits 800-2000€/mois", "Cibler PME locales"],
        "ressources": ["Ahrefs", "Semrush", "Screaming Frog"],
        "warning": "Clients impatients, préparez-les aux délais de 3-6 mois"
    },
    "agence_ads": {
        "nom": "Agence Publicité (Google/Meta Ads)",
        "categorie": "Agence",
        "description": "Gestion de campagnes publicitaires pour clients",
        "revenus_potentiels": "4 000 - 12 000€/mois",
        "revenus_median": "6 000€/mois",
        "temps_objectif_5k": "4-10 mois",
        "capital_requis": "1 000 - 3 000€",
        "scalabilite": 4,
        "realisme": 4,
        "competences_requises": ["Marketing digital/SEO/Ads"],
        "competences_bonus": ["Rédaction/Copywriting", "Design graphique/UI-UX"],
        "modele_revenu": "Prestations de service (freelance, consulting)",
        "type_client": "B2B - Entreprises/Professionnels",
        "lieu": ["100% à domicile/remote", "Nomade digital - depuis n'importe où"],
        "visibilite": ["Oui, je veux être le visage de mon business"],
        "risque": 2,
        "avantages": ["Résultats rapides et mesurables", "Demande e-commerce forte", "Honoraires + % budget"],
        "inconvenients": ["Pression sur ROAS", "Budgets variables", "Plateformes évoluent vite"],
        "etapes_demarrage": ["Certifications Meta/Google", "2-3 cas clients avec chiffres", "Cibler e-commerce 10-50k€ CA", "1000€ fixe + 10-15% budget"],
        "ressources": ["Meta Blueprint", "Google Ads", "Triple Whale"],
        "warning": "Sans résultats prouvés, difficile de convaincre"
    },
    "agence_web": {
        "nom": "Agence Création de Sites Web",
        "categorie": "Agence",
        "description": "Création de sites vitrines et e-commerce pour PME",
        "revenus_potentiels": "5 000 - 15 000€ CA/mois",
        "revenus_median": "8 000€ CA/mois",
        "ca_objectif_5k_net": "8 500€ CA/mois",
        "temps_objectif_5k": "5-12 mois",
        "capital_requis": "500 - 2 000€",
        "scalabilite": 3,
        "realisme": 5,
        "competences_requises": ["Développement web/mobile"],
        "competences_bonus": ["Design graphique/UI-UX", "Vente/Négociation"],
        "modele_revenu": "Prestations de service (freelance, consulting)",
        "type_client": "B2B - Entreprises/Professionnels",
        "lieu": ["100% à domicile/remote", "Principalement à domicile avec déplacements occasionnels"],
        "visibilite": ["Modérément - je préfère rester en retrait"],
        "risque": 2,
        "avantages": ["Demande locale constante", "Maintenance récurrente", "Upsell SEO/hébergement"],
        "inconvenients": ["Concurrence Wix/Squarespace", "Clients non-tech difficiles", "Scope creep"],
        "etapes_demarrage": ["WordPress ou Webflow maîtrisé", "5 sites portfolio", "Cibler PME locales", "Pack 3000-6000€ tout inclus"],
        "ressources": ["WordPress", "Webflow", "Elementor"],
        "warning": "2 sites 4k€ + 5 maintenances 150€ = 8.75k CA → 5.1k NET"
    },
    "agence_recrutement": {
        "nom": "Cabinet de Recrutement Spécialisé",
        "categorie": "Agence",
        "description": "Recrutement pour entreprises dans une niche",
        "revenus_potentiels": "5 000 - 20 000€/mois",
        "revenus_median": "8 000€/mois",
        "temps_objectif_5k": "6-12 mois",
        "capital_requis": "2 000 - 8 000€",
        "scalabilite": 4,
        "realisme": 4,
        "competences_requises": ["Networking/Création de contacts", "Vente/Négociation"],
        "competences_bonus": ["Communication/Prise de parole"],
        "modele_revenu": "Prestations de service (freelance, consulting)",
        "type_client": "B2B - Entreprises/Professionnels",
        "lieu": ["100% à domicile/remote", "Principalement à domicile avec déplacements occasionnels"],
        "visibilite": ["Oui, je veux être le visage de mon business"],
        "risque": 2,
        "avantages": ["Commissions 15-20% salaire brut", "Pas de stock", "Relationnel"],
        "inconvenients": ["Cycle long (2-3 mois)", "Dépendant économie", "Garantie remplacement"],
        "etapes_demarrage": ["Niche sectorielle (tech, finance, santé)", "LinkedIn Recruiter", "Base candidats", "Prospection entreprises"],
        "ressources": ["LinkedIn Recruiter", "Welcome to the Jungle"],
        "warning": "Un placement tech senior = 8-15k€, mais cycle de 2-3 mois"
    },
    "automatisation_ia": {
        "nom": "Consultant Automatisation/IA (Make, n8n)",
        "categorie": "Agence",
        "description": "Automatisation de process avec outils no-code et IA générative",
        "revenus_potentiels": "5 000 - 15 000€ CA/mois",
        "revenus_median": "8 000€ CA/mois",
        "ca_objectif_5k_net": "8 500€ CA/mois",
        "temps_objectif_5k": "3-6 mois",
        "capital_requis": "0 - 1 000€",
        "scalabilite": 3,
        "realisme": 5,
        "competences_requises": [],
        "competences_bonus": ["Développement web/mobile", "Résolution de problèmes"],
        "modele_revenu": "Prestations de service (freelance, consulting)",
        "type_client": "B2B - Entreprises/Professionnels",
        "lieu": ["100% à domicile/remote", "Nomade digital - depuis n'importe où"],
        "visibilite": ["Oui, mais uniquement sur certains canaux"],
        "risque": 1,
        "tendances": ["IA Générative / Agents IA", "Automatisation business (Make, n8n, Zapier)"],
        "avantages": ["TRÈS forte demande 2026", "TJM 800-1500€ réaliste", "PME en retard = opportunité"],
        "inconvenients": ["Outils évoluent vite", "Formation continue", "Concurrence croissante"],
        "etapes_demarrage": ["Maîtriser Make + n8n (2-4 semaines)", "Intégrer Claude/GPT dans workflows", "3 cas concrets", "Cibler PME 10-50 employés"],
        "ressources": ["Make.com", "n8n.io", "Anthropic Claude API", "OpenAI API"],
        "warning": "TJM 1000€ x 9j/mois = 9k CA → 5.3k NET. Très réaliste 2026."
    },
    "agent_ia_builder": {
        "nom": "Créateur d'Agents IA",
        "categorie": "Tech",
        "description": "Développement d'agents IA personnalisés pour entreprises (chatbots, assistants, automatisation)",
        "revenus_potentiels": "6 000 - 20 000€ CA/mois",
        "revenus_median": "10 000€ CA/mois",
        "ca_objectif_5k_net": "8 500€ CA/mois",
        "temps_objectif_5k": "4-8 mois",
        "capital_requis": "0 - 2 000€",
        "scalabilite": 4,
        "realisme": 4,
        "competences_requises": ["Développement web/mobile"],
        "competences_bonus": ["Marketing digital/SEO/Ads", "Résolution de problèmes"],
        "modele_revenu": "Prestations de service (freelance, consulting)",
        "type_client": "B2B - Entreprises/Professionnels",
        "lieu": ["100% à domicile/remote", "Nomade digital - depuis n'importe où"],
        "visibilite": ["Modérément - je préfère rester en retrait"],
        "risque": 2,
        "tendances": ["IA Générative / Agents IA", "Automatisation business (Make, n8n, Zapier)"],
        "avantages": ["Marché explosif 2026", "Tarifs 5-15k€/agent", "Récurrence maintenance 500-1500€/mois", "Peu de concurrence qualifiée"],
        "inconvenients": ["Compétences techniques requises", "Technologie qui évolue vite", "Support client"],
        "etapes_demarrage": ["Maîtriser LangChain/CrewAI/AutoGen", "3 agents démo (support, vente, RH)", "Cibler PME avec process répétitifs", "Forfait création + maintenance mensuelle"],
        "ressources": ["LangChain", "CrewAI", "Claude API", "Vercel AI SDK"],
        "warning": "1 agent 8k€ + 3 maintenances 500€ = 9.5k CA → 5.6k NET"
    },
    "prompt_engineer": {
        "nom": "Consultant IA / Prompt Engineer",
        "categorie": "Agence",
        "description": "Accompagnement entreprises dans l'adoption de l'IA (formation, prompts, stratégie)",
        "revenus_potentiels": "4 000 - 10 000€/mois",
        "revenus_median": "5 500€/mois",
        "temps_objectif_5k": "4-8 mois",
        "capital_requis": "0 - 500€",
        "scalabilite": 3,
        "realisme": 4,
        "competences_requises": ["Communication/Prise de parole"],
        "competences_bonus": ["Pédagogie/Transmission", "Marketing digital/SEO/Ads"],
        "modele_revenu": "Prestations de service (freelance, consulting)",
        "type_client": "B2B - Entreprises/Professionnels",
        "lieu": ["100% à domicile/remote", "Principalement à domicile avec déplacements occasionnels"],
        "visibilite": ["Oui, je veux être le visage de mon business", "Oui, mais uniquement sur certains canaux"],
        "risque": 1,
        "tendances": ["IA Générative / Agents IA", "Prompt Engineering / IA appliquée", "Formation professionnelle / Upskilling"],
        "avantages": ["Demande explosive 2026", "Peu besoin de coder", "Formations + consulting", "Entreprises perdues = opportunité"],
        "inconvenients": ["Crédibilité à construire", "Marché va se professionnaliser", "Veille constante"],
        "etapes_demarrage": ["Expertise Claude/GPT/Midjourney", "Certifications (si dispo)", "3 études de cas", "Cibler RH/Marketing/Direction"],
        "ressources": ["Anthropic", "OpenAI", "LinkedIn (prospection)"],
        "warning": "Window d'opportunité 2024-2026. Positionnez-vous vite."
    },
    "formateur_ia_entreprise": {
        "nom": "Formateur IA en Entreprise",
        "categorie": "Formation",
        "description": "Formations IA pour équipes (prise en main outils, bonnes pratiques, cas d'usage)",
        "revenus_potentiels": "5 000 - 15 000€ CA/mois",
        "revenus_median": "8 000€ CA/mois",
        "ca_objectif_5k_net": "8 500€ CA/mois",
        "temps_objectif_5k": "4-8 mois",
        "capital_requis": "0 - 1 500€",
        "scalabilite": 3,
        "realisme": 5,
        "competences_requises": ["Pédagogie/Transmission", "Communication/Prise de parole"],
        "competences_bonus": ["Développement web/mobile"],
        "modele_revenu": "Prestations de service (freelance, consulting)",
        "type_client": "B2B - Entreprises/Professionnels",
        "lieu": ["100% à domicile/remote", "Principalement à domicile avec déplacements occasionnels"],
        "visibilite": ["Oui, je veux être le visage de mon business"],
        "risque": 1,
        "tendances": ["IA Générative / Agents IA", "Formation professionnelle / Upskilling"],
        "avantages": ["ÉNORME demande 2026", "1500-2500€/jour réaliste", "Récurrence (nouvelles équipes)", "OPCO finançables"],
        "inconvenients": ["Déplacements parfois", "Certification Qualiopi via partenaire", "Contenu à mettre à jour souvent"],
        "etapes_demarrage": ["Créer programme 1-2 jours", "Partenariat organisme certifié Qualiopi", "Cibler DRH/Directions", "LinkedIn + cold email"],
        "ressources": ["LinkedIn", "Organismes Qualiopi", "Supports formation"],
        "warning": "4 jours formation/mois à 2k€ = 8k CA → 4.7k NET. Réaliste."
    },

    # ============================================================
    # COACHING / FORMATION
    # Réaliste si expertise prouvée
    # ============================================================
    "coaching_business": {
        "nom": "Coach Business/Consultant",
        "categorie": "Formation",
        "description": "Accompagnement entrepreneurs et dirigeants TPE",
        "revenus_potentiels": "3 000 - 8 000€/mois",
        "revenus_median": "4 500€/mois",
        "temps_objectif_5k": "6-12 mois",
        "capital_requis": "0 - 2 000€",
        "scalabilite": 3,
        "realisme": 4,
        "competences_requises": ["Communication/Prise de parole", "Écoute et empathie"],
        "competences_bonus": ["Pédagogie/Transmission", "Vente/Négociation"],
        "modele_revenu": "Prestations de service (freelance, consulting)",
        "type_client": "B2B - Entreprises/Professionnels",
        "lieu": ["100% à domicile/remote"],
        "visibilite": ["Oui, je veux être le visage de mon business"],
        "risque": 1,
        "avantages": ["Tarifs 300-800€/mois par client", "Impact réel", "Bouche-à-oreille"],
        "inconvenients": ["Crédibilité à construire", "Énergie intensive", "Limité par le temps"],
        "etapes_demarrage": ["Définir expertise précise", "5-10 clients gratuits/réduits", "Témoignages vidéo", "LinkedIn personal branding"],
        "ressources": ["Calendly", "Zoom", "Notion"],
        "warning": "Sans track record entrepreneurial, difficile de facturer cher"
    },
    "coaching_carriere": {
        "nom": "Coach Carrière/Reconversion",
        "categorie": "Formation",
        "description": "Accompagnement transitions professionnelles",
        "revenus_potentiels": "2 500 - 6 000€/mois",
        "revenus_median": "3 500€/mois",
        "temps_objectif_5k": "8-15 mois",
        "capital_requis": "500 - 2 000€",
        "scalabilite": 3,
        "realisme": 4,
        "competences_requises": ["Écoute et empathie", "Communication/Prise de parole"],
        "competences_bonus": ["Networking/Création de contacts"],
        "modele_revenu": "Prestations de service (freelance, consulting)",
        "type_client": "B2C - Particuliers",
        "lieu": ["100% à domicile/remote"],
        "visibilite": ["Oui, je veux être le visage de mon business"],
        "risque": 1,
        "avantages": ["Forte demande post-covid", "CPF possible", "Impact humain"],
        "inconvenients": ["Certification souvent attendue", "B2C = prospection constante", "Tarifs modérés"],
        "etapes_demarrage": ["Certification coaching reconnue", "Niche (tech, cadres, 40+)", "LinkedIn + Instagram", "Pack 6 séances 800-1500€"],
        "ressources": ["LinkedIn", "ICF", "RNCP certifications"],
        "warning": "Sans certification, crédibilité limitée"
    },
    "formation_en_ligne": {
        "nom": "Formateur en Ligne",
        "categorie": "Formation",
        "description": "Création et vente de formations en ligne",
        "revenus_potentiels": "1 500 - 6 000€/mois",
        "revenus_median": "2 500€/mois",
        "temps_objectif_5k": "12-24 mois",
        "capital_requis": "500 - 3 000€",
        "scalabilite": 4,
        "realisme": 3,
        "competences_requises": ["Pédagogie/Transmission"],
        "competences_bonus": ["Marketing digital/SEO/Ads", "Vidéo/Montage"],
        "modele_revenu": "Vente de produits digitaux (formations, ebooks)",
        "type_client": "B2C - Particuliers",
        "lieu": ["100% à domicile/remote", "Nomade digital - depuis n'importe où"],
        "visibilite": ["Oui, je veux être le visage de mon business"],
        "risque": 2,
        "avantages": ["Revenus semi-passifs", "Scalable", "Impact"],
        "inconvenients": ["Audience à construire (6-18 mois)", "Marché saturé", "Marketing constant"],
        "etapes_demarrage": ["Expertise monétisable validée", "Audience 1000+ (newsletter/YouTube)", "Première formation 200-500€", "Tunnel de vente"],
        "ressources": ["Podia", "Systeme.io", "Teachable"],
        "warning": "80% des créateurs font < 500€/mois. L'audience AVANT le produit."
    },
    "mentor_tech": {
        "nom": "Mentor/Tuteur Tech",
        "categorie": "Formation",
        "description": "Mentorat développeurs juniors et reconversions",
        "revenus_potentiels": "1 500 - 4 000€/mois",
        "revenus_median": "2 500€/mois",
        "temps_objectif_5k": "10-18 mois",
        "capital_requis": "0 - 500€",
        "scalabilite": 2,
        "realisme": 4,
        "competences_requises": ["Développement web/mobile", "Pédagogie/Transmission"],
        "competences_bonus": [],
        "modele_revenu": "Prestations de service (freelance, consulting)",
        "type_client": "B2C - Particuliers",
        "lieu": ["100% à domicile/remote"],
        "visibilite": ["Oui, mais uniquement sur certains canaux"],
        "risque": 1,
        "avantages": ["Plateformes existantes", "Sessions courtes", "Complément freelance"],
        "inconvenients": ["Tarifs plafonnés 50-100€/h", "Volume nécessaire", "Horaires variables"],
        "etapes_demarrage": ["Profil Codementor/MentorCruise", "Spécialité (React, Python, etc.)", "50-80€/h au début", "Augmenter avec reviews"],
        "ressources": ["Codementor", "MentorCruise", "ADPList"],
        "warning": "Bon complément mais rarement suffisant seul pour 5k€"
    },

    # ============================================================
    # E-COMMERCE
    # Capital requis, risque modéré
    # ============================================================
    "ecommerce_marque": {
        "nom": "E-commerce Marque Propre",
        "categorie": "E-commerce",
        "description": "Création et vente de produits sous sa propre marque",
        "revenus_potentiels": "2 000 - 8 000€/mois (net)",
        "revenus_median": "3 500€/mois",
        "temps_objectif_5k": "18-30 mois",
        "capital_requis": "8 000 - 25 000€",
        "scalabilite": 4,
        "realisme": 3,
        "competences_requises": ["Marketing digital/SEO/Ads"],
        "competences_bonus": ["Design graphique/UI-UX", "Gestion de projet"],
        "modele_revenu": "Vente de produits physiques",
        "type_client": "B2C - Particuliers",
        "lieu": ["100% à domicile/remote", "Local commercial/Bureau"],
        "visibilite": ["Non - je veux un business anonyme/discret", "Modérément - je préfère rester en retrait"],
        "risque": 3,
        "avantages": ["Asset revendable", "Marges 40-60%", "Scalable"],
        "inconvenients": ["Capital important", "Stock/logistique", "Ads coûteuses"],
        "etapes_demarrage": ["Niche validée (étude marché)", "Fournisseur fiable", "Shopify + 3PL", "Test Ads petit budget"],
        "ressources": ["Shopify", "Alibaba", "BigBuy (EU)"],
        "warning": "Prévoir 6-12 mois avant rentabilité. Beaucoup échouent."
    },
    "vente_etsy": {
        "nom": "Boutique Etsy/Artisanat",
        "categorie": "E-commerce",
        "description": "Vente d'articles faits main, vintage ou digitaux",
        "revenus_potentiels": "1 000 - 4 000€/mois",
        "revenus_median": "1 800€/mois",
        "temps_objectif_5k": "18-36 mois",
        "capital_requis": "500 - 3 000€",
        "scalabilite": 3,
        "realisme": 3,
        "competences_requises": ["Artisanat/Manuel"],
        "competences_bonus": ["Design graphique/UI-UX", "Marketing digital/SEO/Ads"],
        "modele_revenu": "Vente de produits physiques",
        "type_client": "B2C - Particuliers",
        "lieu": ["100% à domicile/remote"],
        "visibilite": ["Non - je veux un business anonyme/discret"],
        "risque": 2,
        "passions": ["Art/Créativité"],
        "avantages": ["Trafic Etsy gratuit", "Communauté créative", "Produits digitaux possibles"],
        "inconvenients": ["Frais Etsy 15-20%", "Création chronophage", "Concurrence mondiale"],
        "etapes_demarrage": ["Produit unique/différenciant", "Photos professionnelles", "SEO Etsy optimisé", "50+ produits"],
        "ressources": ["Etsy", "eRank", "Canva"],
        "warning": "Les produits digitaux (templates) sont plus scalables"
    },
    "revente_occasions": {
        "nom": "Revente/Flipping Spécialisé",
        "categorie": "E-commerce",
        "description": "Achat-revente d'objets à profit dans une niche",
        "revenus_potentiels": "1 500 - 5 000€/mois",
        "revenus_median": "2 500€/mois",
        "temps_objectif_5k": "8-15 mois",
        "capital_requis": "2 000 - 8 000€",
        "scalabilite": 2,
        "realisme": 4,
        "competences_requises": ["Vente/Négociation"],
        "competences_bonus": [],
        "modele_revenu": "Vente de produits physiques",
        "type_client": "B2C - Particuliers",
        "lieu": ["Principalement à domicile avec déplacements occasionnels"],
        "visibilite": ["Non - je veux un business anonyme/discret"],
        "risque": 2,
        "tendances": ["Seconde main/Économie circulaire"],
        "avantages": ["Démarrage rapide", "Expertise = marge", "Cash flow positif"],
        "inconvenients": ["Temps sourcing important", "Stockage", "Pas scalable infini"],
        "etapes_demarrage": ["Niche expertise (meubles, tech, vintage)", "Sourcing brocantes/LBC", "Vinted/eBay/LBC", "Marge mini 50%"],
        "ressources": ["Vinted", "eBay", "Leboncoin"],
        "warning": "Temps de sourcing souvent sous-estimé"
    },

    # ============================================================
    # TECH / SAAS
    # Long terme mais très scalable
    # ============================================================
    "saas_micro": {
        "nom": "Micro-SaaS",
        "categorie": "Tech",
        "description": "Petit logiciel résolvant un problème spécifique",
        "revenus_potentiels": "1 000 - 5 000€/mois",
        "revenus_median": "2 000€/mois",
        "temps_objectif_5k": "18-36 mois",
        "capital_requis": "0 - 3 000€",
        "scalabilite": 5,
        "realisme": 3,
        "competences_requises": ["Développement web/mobile"],
        "competences_bonus": ["Marketing digital/SEO/Ads", "Design graphique/UI-UX"],
        "modele_revenu": "Abonnements/Revenus récurrents (SaaS, membership)",
        "type_client": "B2B - Entreprises/Professionnels",
        "lieu": ["100% à domicile/remote", "Nomade digital - depuis n'importe où"],
        "visibilite": ["Non - je veux un business anonyme/discret"],
        "risque": 3,
        "tendances": ["Intelligence Artificielle", "Automatisation/No-code"],
        "avantages": ["MRR prévisible", "Très scalable", "Asset valorisé 3-5x ARR"],
        "inconvenients": ["Long à développer", "Support client", "Churn à gérer"],
        "etapes_demarrage": ["Problème validé (10 prospects)", "MVP en 1-2 mois", "10 premiers clients payants", "Itérer"],
        "ressources": ["Indie Hackers", "MicroConf", "Stripe"],
        "warning": "90% des SaaS échouent. Validez AVANT de coder."
    },
    "saas_nocode": {
        "nom": "SaaS/App No-Code",
        "categorie": "Tech",
        "description": "Application créée avec outils no-code",
        "revenus_potentiels": "800 - 3 000€/mois",
        "revenus_median": "1 500€/mois",
        "temps_objectif_5k": "24-36 mois",
        "capital_requis": "500 - 2 000€",
        "scalabilite": 4,
        "realisme": 2,
        "competences_requises": [],
        "competences_bonus": ["Design graphique/UI-UX", "Marketing digital/SEO/Ads"],
        "modele_revenu": "Abonnements/Revenus récurrents (SaaS, membership)",
        "type_client": "Les deux me conviennent",
        "lieu": ["100% à domicile/remote", "Nomade digital - depuis n'importe où"],
        "visibilite": ["Modérément - je préfère rester en retrait"],
        "risque": 2,
        "tendances": ["Automatisation/No-code"],
        "avantages": ["Pas besoin de coder", "Lancement rapide", "Test d'idées"],
        "inconvenients": ["Limitations techniques", "Coûts outils mensuels", "Scalabilité limitée"],
        "etapes_demarrage": ["Apprendre Bubble/Webflow (2-3 mois)", "Problème niche simple", "MVP", "Valider avant d'aller loin"],
        "ressources": ["Bubble.io", "Webflow", "Glide"],
        "warning": "Bon pour valider, mais limites techniques si ça marche"
    },
    "template_themes": {
        "nom": "Vente de Templates/Thèmes",
        "categorie": "Tech",
        "description": "Création et vente de templates Notion, Figma, WordPress...",
        "revenus_potentiels": "300 - 2 000€/mois",
        "revenus_median": "800€/mois",
        "temps_objectif_5k": "24-48 mois",
        "capital_requis": "0 - 500€",
        "scalabilite": 4,
        "realisme": 2,
        "competences_requises": ["Design graphique/UI-UX"],
        "competences_bonus": ["Développement web/mobile", "Marketing digital/SEO/Ads"],
        "modele_revenu": "Vente de produits digitaux (formations, ebooks)",
        "type_client": "Les deux me conviennent",
        "lieu": ["100% à domicile/remote", "Nomade digital - depuis n'importe où"],
        "visibilite": ["Non - je veux un business anonyme/discret"],
        "risque": 2,
        "avantages": ["Revenus passifs", "Création unique", "Pas de support lourd"],
        "inconvenients": ["Concurrence forte", "Volume nécessaire", "IA génère des templates 2026"],
        "etapes_demarrage": ["Niche template (Notion productivity, Figma UI kits)", "5-10 templates qualité", "Gumroad + Twitter", "SEO Notion/Figma"],
        "ressources": ["Gumroad", "Notion", "Figma Community"],
        "warning": "Marché saturé, différenciez-vous par la qualité"
    },

    # ============================================================
    # CONTENU / MÉDIA
    # Long terme, audience requise
    # ============================================================
    "newsletter_sponsorisee": {
        "nom": "Newsletter B2B Sponsorisée",
        "categorie": "Contenu",
        "description": "Newsletter gratuite monétisée par sponsors",
        "revenus_potentiels": "1 500 - 6 000€/mois",
        "revenus_median": "2 500€/mois",
        "temps_objectif_5k": "18-30 mois",
        "capital_requis": "0 - 500€",
        "scalabilite": 4,
        "realisme": 3,
        "competences_requises": ["Rédaction/Copywriting"],
        "competences_bonus": ["Marketing digital/SEO/Ads", "Vente/Négociation"],
        "modele_revenu": "Publicité/Contenu sponsorisé",
        "type_client": "B2B - Entreprises/Professionnels",
        "lieu": ["100% à domicile/remote", "Nomade digital - depuis n'importe où"],
        "visibilite": ["Oui, je veux être le visage de mon business"],
        "risque": 2,
        "avantages": ["CPM B2B élevés (30-50€)", "Asset vendable", "Relation directe audience"],
        "inconvenients": ["5-10k abonnés minimum", "Croissance lente", "Régularité obligatoire"],
        "etapes_demarrage": ["Niche B2B (finance, tech, RH)", "Croissance organique + referral", "10k abonnés = premiers sponsors", "CPM 30-50€"],
        "ressources": ["Beehiiv", "Sparkloop", "Swapstack"],
        "warning": "CPM réaliste: 30-50€/1000 abonnés en B2B France"
    },
    "blogging_seo": {
        "nom": "Site de Niche SEO",
        "categorie": "Contenu",
        "description": "Site de contenu monétisé par affiliation/pubs",
        "revenus_potentiels": "800 - 3 000€/mois",
        "revenus_median": "1 200€/mois",
        "temps_objectif_5k": "30-48 mois",
        "capital_requis": "1 000 - 5 000€",
        "scalabilite": 4,
        "realisme": 2,
        "competences_requises": ["Rédaction/Copywriting", "Marketing digital/SEO/Ads"],
        "competences_bonus": [],
        "modele_revenu": "Affiliation/Commission",
        "type_client": "Pas de contact client direct (produits automatisés)",
        "lieu": ["100% à domicile/remote", "Nomade digital - depuis n'importe où"],
        "visibilite": ["Non - je veux un business anonyme/discret"],
        "risque": 4,
        "avantages": ["Revenus passifs", "Asset vendable 30-40x mensuel", "Scalable avec rédacteurs"],
        "inconvenients": ["SEO = 12-24 mois", "Google updates risque", "IA bouleverse le SEO 2026"],
        "etapes_demarrage": ["Niche avec affiliation rentable", "50-100 articles SEO", "Backlinks qualité", "Patience 18-24 mois"],
        "ressources": ["Ahrefs", "Semrush", "Ezoic"],
        "warning": "Premier euro après 6-12 mois minimum. Patience requise."
    },
    "podcast_b2b": {
        "nom": "Podcast B2B + Services",
        "categorie": "Contenu",
        "description": "Podcast comme levier pour vendre des services",
        "revenus_potentiels": "3 000 - 8 000€/mois (via services)",
        "revenus_median": "4 000€/mois",
        "temps_objectif_5k": "12-24 mois",
        "capital_requis": "500 - 2 000€",
        "scalabilite": 3,
        "realisme": 4,
        "competences_requises": ["Communication/Prise de parole"],
        "competences_bonus": ["Networking/Création de contacts", "Vente/Négociation"],
        "modele_revenu": "Prestations de service (freelance, consulting)",
        "type_client": "B2B - Entreprises/Professionnels",
        "lieu": ["100% à domicile/remote"],
        "visibilite": ["Oui, je veux être le visage de mon business"],
        "risque": 2,
        "avantages": ["Crédibilité expert", "Réseau via invités", "Leads qualifiés"],
        "inconvenients": ["Monétisation directe faible", "Régularité requise", "Production chronophage"],
        "etapes_demarrage": ["Niche expertise", "Micro correct (200€)", "Invités = réseau", "CTA vers services"],
        "ressources": ["Riverside.fm", "Descript", "Ausha"],
        "warning": "Le podcast génère des leads, pas des revenus directs"
    },

    # ============================================================
    # IMMOBILIER
    # Capital important mais revenus stables
    # ============================================================
    "immobilier_lcd": {
        "nom": "Location Courte Durée (LCD)",
        "categorie": "Immobilier",
        "description": "Location saisonnière type Airbnb",
        "revenus_potentiels": "800 - 2 500€/mois (par bien, net)",
        "revenus_median": "1 200€/mois par bien",
        "temps_objectif_5k": "24-36 mois (multi-biens)",
        "capital_requis": "20 000 - 60 000€ (apport)",
        "scalabilite": 3,
        "realisme": 4,
        "competences_requises": ["Immobilier", "Organisation/Rigueur"],
        "competences_bonus": [],
        "modele_revenu": "Abonnements/Revenus récurrents (SaaS, membership)",
        "type_client": "B2C - Particuliers",
        "lieu": ["Principalement à domicile avec déplacements occasionnels"],
        "visibilite": ["Non - je veux un business anonyme/discret"],
        "risque": 3,
        "passions": ["Immobilier", "Voyage/Tourisme"],
        "avantages": ["Revenus > location classique", "Patrimoine", "Usage perso possible"],
        "inconvenients": ["Capital important", "Réglementation stricte", "Gestion intensive"],
        "etapes_demarrage": ["Zone touristique autorisée", "Bien adapté LCD", "Ameublement qualité", "Pricing dynamique"],
        "ressources": ["Airbnb", "Booking", "PriceLabs"],
        "warning": "Vérifiez la réglementation locale AVANT d'acheter"
    },
    "conciergerie_airbnb": {
        "nom": "Conciergerie Airbnb",
        "categorie": "Immobilier",
        "description": "Gestion de LCD pour propriétaires",
        "revenus_potentiels": "2 000 - 6 000€/mois",
        "revenus_median": "3 000€/mois",
        "temps_objectif_5k": "8-15 mois",
        "capital_requis": "1 000 - 5 000€",
        "scalabilite": 3,
        "realisme": 4,
        "competences_requises": ["Organisation/Rigueur"],
        "competences_bonus": ["Négociation", "Networking/Création de contacts"],
        "modele_revenu": "Prestations de service (freelance, consulting)",
        "type_client": "B2B - Entreprises/Professionnels",
        "lieu": ["Sur le terrain/Chez les clients", "Principalement à domicile avec déplacements occasionnels"],
        "visibilite": ["Modérément - je préfère rester en retrait"],
        "risque": 2,
        "passions": ["Immobilier"],
        "avantages": ["Pas d'achat immo", "15-25% des revenus", "Récurrence"],
        "inconvenients": ["Disponibilité 7j/7", "Équipe ménage à gérer", "Saisonnalité"],
        "etapes_demarrage": ["Étude marché local", "3-5 premiers biens", "Équipe ménage fiable", "15-20% commission"],
        "ressources": ["Lodgify", "Guesty", "Hostaway"],
        "warning": "15-20 biens nécessaires pour 5k€ net"
    },
    "immobilier_colocation": {
        "nom": "Colocation Meublée",
        "categorie": "Immobilier",
        "description": "Location en colocation pour maximiser rendement",
        "revenus_potentiels": "800 - 2 000€/mois (par bien, net)",
        "revenus_median": "1 000€/mois par bien",
        "temps_objectif_5k": "36-48 mois (3-5 biens)",
        "capital_requis": "25 000 - 70 000€ (apport)",
        "scalabilite": 3,
        "realisme": 4,
        "competences_requises": ["Immobilier"],
        "competences_bonus": ["Organisation/Rigueur"],
        "modele_revenu": "Abonnements/Revenus récurrents (SaaS, membership)",
        "type_client": "B2C - Particuliers",
        "lieu": ["Principalement à domicile avec déplacements occasionnels"],
        "visibilite": ["Non - je veux un business anonyme/discret"],
        "risque": 3,
        "passions": ["Immobilier"],
        "avantages": ["Rendement 8-12% brut", "LMNP avantageux", "Demande étudiante"],
        "inconvenients": ["Gestion turnover", "Travaux aménagement", "Rotation locataires"],
        "etapes_demarrage": ["Ville universitaire", "T4-T5 bien placé", "Chambres équipées", "Bail individuel par chambre"],
        "ressources": ["Appartager", "La Carte des Colocs"],
        "warning": "Rendement brut ≠ net. Comptez charges, vacance, travaux."
    },

    # ============================================================
    # SERVICES LOCAUX
    # Très réalistes, scalables avec équipe
    # ============================================================
    "nettoyage_entreprises": {
        "nom": "Entreprise de Nettoyage B2B",
        "categorie": "Services locaux",
        "description": "Nettoyage bureaux et locaux professionnels",
        "revenus_potentiels": "4 000 - 12 000€/mois",
        "revenus_median": "6 000€/mois",
        "temps_objectif_5k": "6-12 mois",
        "capital_requis": "3 000 - 10 000€",
        "scalabilite": 4,
        "realisme": 5,
        "competences_requises": ["Organisation/Rigueur"],
        "competences_bonus": ["Leadership/Management", "Vente/Négociation"],
        "modele_revenu": "Prestations de service (freelance, consulting)",
        "type_client": "B2B - Entreprises/Professionnels",
        "lieu": ["Sur le terrain/Chez les clients"],
        "visibilite": ["Modérément - je préfère rester en retrait"],
        "risque": 2,
        "avantages": ["Récurrence garantie", "Contrats 12-24 mois", "Scalable"],
        "inconvenients": ["Gestion personnel", "Horaires décalés", "Marge sur MO"],
        "etapes_demarrage": ["Équipement pro", "1er client (réseau)", "Employé fiable", "Contrats récurrents"],
        "ressources": ["Matériel pro", "Logiciel planning"],
        "warning": "Marge réelle 20-35% après charges et personnel"
    },
    "services_seniors": {
        "nom": "Services aux Seniors",
        "categorie": "Services locaux",
        "description": "Aide à domicile, courses, accompagnement",
        "revenus_potentiels": "3 000 - 8 000€/mois",
        "revenus_median": "4 500€/mois",
        "temps_objectif_5k": "8-15 mois",
        "capital_requis": "2 000 - 8 000€",
        "scalabilite": 3,
        "realisme": 5,
        "competences_requises": ["Écoute et empathie", "Organisation/Rigueur"],
        "competences_bonus": ["Leadership/Management"],
        "modele_revenu": "Prestations de service (freelance, consulting)",
        "type_client": "B2C - Particuliers",
        "lieu": ["Sur le terrain/Chez les clients"],
        "visibilite": ["Modérément - je préfère rester en retrait"],
        "risque": 1,
        "tendances": ["Services aux seniors"],
        "avantages": ["Marché en croissance forte", "Aides APA/crédit impôt", "Impact social"],
        "inconvenients": ["Agrément SAP requis", "Émotionnel", "Personnel à gérer"],
        "etapes_demarrage": ["Agrément services à la personne", "Zone géographique", "Partenariats CCAS/mutuelles", "Équipe"],
        "ressources": ["DIRECCTE", "CCAS", "Fédération SAP"],
        "warning": "Agrément obligatoire pour avantages fiscaux clients"
    },
    "renovation_bricolage": {
        "nom": "Services Rénovation/Bricolage",
        "categorie": "Services locaux",
        "description": "Petits travaux et rénovation pour particuliers",
        "revenus_potentiels": "3 000 - 7 000€/mois",
        "revenus_median": "4 500€/mois",
        "temps_objectif_5k": "4-10 mois",
        "capital_requis": "3 000 - 10 000€",
        "scalabilite": 2,
        "realisme": 5,
        "competences_requises": ["Artisanat/Manuel"],
        "competences_bonus": ["Vente/Négociation"],
        "modele_revenu": "Prestations de service (freelance, consulting)",
        "type_client": "B2C - Particuliers",
        "lieu": ["Sur le terrain/Chez les clients"],
        "visibilite": ["Modérément - je préfère rester en retrait"],
        "risque": 2,
        "avantages": ["Forte demande", "Tarifs 30-50€/h", "Bouche-à-oreille"],
        "inconvenients": ["Physique", "Assurance obligatoire", "Aléas chantiers"],
        "etapes_demarrage": ["Définir prestations (peinture, montage, etc.)", "Assurance RC Pro", "Leboncoin Services", "Avis Google"],
        "ressources": ["Frizbiz", "Leboncoin Services", "Needhelp"],
        "warning": "Certains travaux nécessitent qualifications (électricité, plomberie)"
    },
    "jardinage_paysagiste": {
        "nom": "Jardinier/Entretien Espaces Verts",
        "categorie": "Services locaux",
        "description": "Entretien jardins particuliers et entreprises",
        "revenus_potentiels": "2 500 - 6 000€/mois",
        "revenus_median": "3 500€/mois",
        "temps_objectif_5k": "8-15 mois",
        "capital_requis": "4 000 - 12 000€",
        "scalabilite": 3,
        "realisme": 4,
        "competences_requises": ["Artisanat/Manuel"],
        "competences_bonus": ["Vente/Négociation"],
        "modele_revenu": "Prestations de service (freelance, consulting)",
        "type_client": "Les deux me conviennent",
        "lieu": ["Sur le terrain/Chez les clients"],
        "visibilite": ["Modérément - je préfère rester en retrait"],
        "risque": 2,
        "avantages": ["Travail extérieur", "Clients récurrents", "Crédit d'impôt SAP"],
        "inconvenients": ["Saisonnalité mars-octobre", "Météo", "Physique"],
        "etapes_demarrage": ["Équipement (tondeuse, taille-haie)", "Agrément SAP", "Quartiers résidentiels", "Contrats annuels"],
        "ressources": ["Matériel jardinage pro", "CESU"],
        "warning": "Activité saisonnière, prévoir trésorerie hiver"
    },
    "lavage_auto": {
        "nom": "Lavage Auto/Detailing à Domicile",
        "categorie": "Services locaux",
        "description": "Nettoyage automobile sur site client",
        "revenus_potentiels": "2 500 - 6 000€/mois",
        "revenus_median": "3 500€/mois",
        "temps_objectif_5k": "8-15 mois",
        "capital_requis": "4 000 - 12 000€",
        "scalabilite": 3,
        "realisme": 4,
        "competences_requises": ["Organisation/Rigueur"],
        "competences_bonus": [],
        "modele_revenu": "Prestations de service (freelance, consulting)",
        "type_client": "Les deux me conviennent",
        "lieu": ["Sur le terrain/Chez les clients"],
        "visibilite": ["Modérément - je préfère rester en retrait"],
        "risque": 2,
        "passions": ["Automobile"],
        "avantages": ["Service premium différenciant", "Flottes entreprises", "Écologique"],
        "inconvenients": ["Équipement mobile", "Météo", "Déplacements"],
        "etapes_demarrage": ["Équipement detailing", "Produits sans eau/écolo", "Cibler entreprises (flottes)", "Abonnements mensuels"],
        "ressources": ["Équipement detailing", "Produits écologiques"],
        "warning": "Le B2B (flottes) est plus rentable que le B2C"
    },

    # ============================================================
    # FOOD / RESTAURATION
    # Capital et réglementation
    # ============================================================
    "traiteur": {
        "nom": "Traiteur/Chef à Domicile",
        "categorie": "Food",
        "description": "Services de traiteur événementiel",
        "revenus_potentiels": "3 000 - 8 000€/mois",
        "revenus_median": "4 500€/mois",
        "temps_objectif_5k": "8-15 mois",
        "capital_requis": "5 000 - 15 000€",
        "scalabilite": 3,
        "realisme": 4,
        "competences_requises": ["Cuisine/Restauration"],
        "competences_bonus": ["Organisation/Rigueur", "Vente/Négociation"],
        "modele_revenu": "Prestations de service (freelance, consulting)",
        "type_client": "Les deux me conviennent",
        "lieu": ["Sur le terrain/Chez les clients"],
        "visibilite": ["Oui, mais uniquement sur certains canaux"],
        "risque": 2,
        "passions": ["Food/Restauration"],
        "avantages": ["Paniers 50-150€/personne", "Bouche-à-oreille", "Événements récurrents"],
        "inconvenients": ["Pics d'activité WE", "Logistique", "Normes sanitaires"],
        "etapes_demarrage": ["Formation hygiène HACCP", "Cuisine aux normes", "Photos portfolio", "Mariages + entreprises"],
        "ressources": ["La Belle Assiette", "Instagram"],
        "warning": "Agrément sanitaire obligatoire"
    },
    "produits_alimentaires": {
        "nom": "Production Alimentaire Artisanale",
        "categorie": "Food",
        "description": "Fabrication et vente de produits (confitures, biscuits...)",
        "revenus_potentiels": "1 500 - 5 000€/mois",
        "revenus_median": "2 500€/mois",
        "temps_objectif_5k": "18-30 mois",
        "capital_requis": "8 000 - 25 000€",
        "scalabilite": 3,
        "realisme": 3,
        "competences_requises": ["Cuisine/Restauration"],
        "competences_bonus": ["Marketing digital/SEO/Ads"],
        "modele_revenu": "Vente de produits physiques",
        "type_client": "Les deux me conviennent",
        "lieu": ["Local commercial/Bureau"],
        "visibilite": ["Oui, mais uniquement sur certains canaux"],
        "risque": 2,
        "passions": ["Food/Restauration"],
        "avantages": ["Marges artisanales 50-70%", "Multi-canal", "Passion"],
        "inconvenients": ["Normes sanitaires strictes", "DLC à gérer", "Investissement labo"],
        "etapes_demarrage": ["Agrément sanitaire", "Laboratoire (partagé possible)", "Marchés locaux", "Épiceries fines + e-commerce"],
        "ressources": ["Laboratoire partagé", "Marchés locaux"],
        "warning": "Laboratoire aux normes = investissement ou location"
    },

    # ============================================================
    # ÉVÉNEMENTIEL
    # Saisonnier mais rentable
    # ============================================================
    "wedding_planner": {
        "nom": "Wedding Planner",
        "categorie": "Événementiel",
        "description": "Organisation de mariages",
        "revenus_potentiels": "2 500 - 7 000€/mois (lissé)",
        "revenus_median": "4 000€/mois",
        "temps_objectif_5k": "12-24 mois",
        "capital_requis": "2 000 - 6 000€",
        "scalabilite": 2,
        "realisme": 4,
        "competences_requises": ["Organisation/Rigueur"],
        "competences_bonus": ["Créativité/Innovation", "Négociation"],
        "modele_revenu": "Prestations de service (freelance, consulting)",
        "type_client": "B2C - Particuliers",
        "lieu": ["Principalement à domicile avec déplacements occasionnels", "Sur le terrain/Chez les clients"],
        "visibilite": ["Oui, je veux être le visage de mon business"],
        "risque": 2,
        "avantages": ["2000-5000€/mariage", "Passion", "Recommandations"],
        "inconvenients": ["Saisonnalité mai-sept", "Stress jour J", "WE occupés"],
        "etapes_demarrage": ["Formation wedding planner", "3-5 mariages (ami/réduit)", "Portfolio Instagram", "Réseau prestataires"],
        "ressources": ["Mariages.net", "Pinterest", "Instagram"],
        "warning": "10-15 mariages/an réaliste au début. Saisonnalité forte."
    },
    "event_entreprise": {
        "nom": "Organisateur Événements B2B",
        "categorie": "Événementiel",
        "description": "Organisation séminaires, team buildings",
        "revenus_potentiels": "4 000 - 12 000€/mois",
        "revenus_median": "6 000€/mois",
        "temps_objectif_5k": "8-15 mois",
        "capital_requis": "3 000 - 10 000€",
        "scalabilite": 3,
        "realisme": 4,
        "competences_requises": ["Organisation/Rigueur", "Vente/Négociation"],
        "competences_bonus": ["Créativité/Innovation", "Networking/Création de contacts"],
        "modele_revenu": "Prestations de service (freelance, consulting)",
        "type_client": "B2B - Entreprises/Professionnels",
        "lieu": ["Principalement à domicile avec déplacements occasionnels"],
        "visibilite": ["Oui, je veux être le visage de mon business"],
        "risque": 2,
        "avantages": ["Budgets 5-50k€/event", "Récurrence annuelle", "B2B = paiement fiable"],
        "inconvenients": ["Cycle de vente long", "Responsabilité", "Disponibilité"],
        "etapes_demarrage": ["Niche (tech, RH, etc.)", "Réseau lieux/prestataires", "Prospection DRH/COM", "3 références"],
        "ressources": ["LinkedIn", "EventMB"],
        "warning": "Un event = 1-3 mois de préparation. Gérer le pipeline."
    },
    "photographe": {
        "nom": "Photographe Pro (Corporate/Événement)",
        "categorie": "Événementiel",
        "description": "Photos corporate, événements, portraits pro",
        "revenus_potentiels": "2 500 - 6 000€/mois",
        "revenus_median": "3 500€/mois",
        "temps_objectif_5k": "10-18 mois",
        "capital_requis": "5 000 - 15 000€",
        "scalabilite": 2,
        "realisme": 4,
        "competences_requises": ["Vidéo/Montage"],
        "competences_bonus": ["Marketing digital/SEO/Ads", "Networking/Création de contacts"],
        "modele_revenu": "Prestations de service (freelance, consulting)",
        "type_client": "Les deux me conviennent",
        "lieu": ["Sur le terrain/Chez les clients"],
        "visibilite": ["Oui, je veux être le visage de mon business"],
        "risque": 2,
        "passions": ["Art/Créativité"],
        "avantages": ["Corporate = tarifs stables", "Récurrence possible", "Créativité"],
        "inconvenients": ["Investissement matériel lourd", "Post-traitement long", "Concurrence"],
        "etapes_demarrage": ["Matériel pro (3-5k€ mini)", "Portfolio corporate", "LinkedIn + réseau", "Pack journée 800-1500€"],
        "ressources": ["Instagram", "LinkedIn", "Lightroom"],
        "warning": "Corporate plus stable que mariages (moins saisonnier)"
    }
}

# Nombre total de modèles
TOTAL_MODELS = len(BUSINESS_MODELS)

# Score de réalisme moyen
AVG_REALISME = sum(b.get("realisme", 3) for b in BUSINESS_MODELS.values()) / len(BUSINESS_MODELS)

# Catégories pour le filtrage
CATEGORIES = {
    "freelance": [k for k, v in BUSINESS_MODELS.items() if v.get("categorie") == "Freelance"],
    "agence": [k for k, v in BUSINESS_MODELS.items() if v.get("categorie") == "Agence"],
    "formation": [k for k, v in BUSINESS_MODELS.items() if v.get("categorie") == "Formation"],
    "ecommerce": [k for k, v in BUSINESS_MODELS.items() if v.get("categorie") == "E-commerce"],
    "tech": [k for k, v in BUSINESS_MODELS.items() if v.get("categorie") == "Tech"],
    "contenu": [k for k, v in BUSINESS_MODELS.items() if v.get("categorie") == "Contenu"],
    "immobilier": [k for k, v in BUSINESS_MODELS.items() if v.get("categorie") == "Immobilier"],
    "services_locaux": [k for k, v in BUSINESS_MODELS.items() if v.get("categorie") == "Services locaux"],
    "food": [k for k, v in BUSINESS_MODELS.items() if v.get("categorie") == "Food"],
    "evenementiel": [k for k, v in BUSINESS_MODELS.items() if v.get("categorie") == "Événementiel"],
}

# Business les plus réalistes pour 5k rapidement
FAST_TRACK_5K = [
    "freelance_dev",
    "freelance_marketing",
    "freelance_comptable",
    "agence_web",
    "automatisation_ia",
    "nettoyage_entreprises",
    "renovation_bricolage",
    "formateur_ia_entreprise"
]

# === NOUVEAUX 2026 - Business les plus porteurs ===
HOT_2026 = [
    "automatisation_ia",         # Très forte demande
    "agent_ia_builder",          # Marché explosif
    "prompt_engineer",           # Window d'opportunité
    "formateur_ia_entreprise",   # Demande énorme
    "services_seniors",          # Démographie
    "conciergerie_airbnb",       # LCD toujours porteur
]

# Business à éviter ou en déclin 2026
DECLINING_2026 = [
    "blogging_seo",              # IA change la donne SEO
    "template_themes",           # IA génère des templates
    "freelance_copywriter",      # Concurrence IA forte
]
