"""
Base de données EXHAUSTIVE des modèles de business rentables.
60+ modèles pour objectifs: 5k€ puis 8k€ net/mois
"""

BUSINESS_MODELS = {
    # ============================================================
    # FREELANCE / SERVICES INDIVIDUELS
    # ============================================================
    "freelance_dev": {
        "nom": "Développeur Freelance",
        "categorie": "Freelance",
        "description": "Prestations de développement web/mobile pour des clients",
        "revenus_potentiels": "3 000 - 15 000€/mois",
        "temps_objectif_5k": "3-6 mois",
        "capital_requis": "0 - 500€",
        "scalabilite": 2,
        "competences_requises": ["Développement web/mobile"],
        "competences_bonus": ["Gestion de projet", "Vente/Négociation"],
        "modele_revenu": "Prestations de service (freelance, consulting)",
        "type_client": "B2B - Entreprises/Professionnels",
        "lieu": ["100% à domicile/remote", "Nomade digital - depuis n'importe où"],
        "visibilite": ["Modérément - je préfère rester en retrait", "Non - je veux un business anonyme/discret"],
        "risque": 1,
        "avantages": ["Démarrage rapide", "Faible investissement", "Forte demande", "TJM élevé 400-800€"],
        "inconvenients": ["Échange temps/argent", "Revenus non passifs", "Dépendance clients"],
        "etapes_demarrage": ["Créer portfolio GitHub", "S'inscrire Malt/Comet", "LinkedIn actif", "Définir TJM"],
        "ressources": ["Malt.fr", "Comet.co", "Upwork.com"]
    },
    "freelance_design": {
        "nom": "Designer Freelance (UI/UX/Graphique)",
        "categorie": "Freelance",
        "description": "Création de designs, interfaces, identités visuelles",
        "revenus_potentiels": "2 500 - 10 000€/mois",
        "temps_objectif_5k": "4-8 mois",
        "capital_requis": "500 - 1 500€",
        "scalabilite": 2,
        "competences_requises": ["Design graphique/UI-UX"],
        "competences_bonus": ["Marketing digital/SEO/Ads", "Vidéo/Montage"],
        "modele_revenu": "Prestations de service (freelance, consulting)",
        "type_client": "B2B - Entreprises/Professionnels",
        "lieu": ["100% à domicile/remote", "Nomade digital - depuis n'importe où"],
        "visibilite": ["Modérément - je préfère rester en retrait"],
        "risque": 1,
        "avantages": ["Portfolio visuel impactant", "Clients variés", "Créativité"],
        "inconvenients": ["Subjectivité des retours", "Concurrence Fiverr", "Révisions infinies"],
        "etapes_demarrage": ["Portfolio Behance/Dribbble", "Niche spécifique", "Malt/99designs", "Personal branding"],
        "ressources": ["Behance", "Dribbble", "Figma", "99designs"]
    },
    "freelance_marketing": {
        "nom": "Consultant Marketing Digital",
        "categorie": "Freelance",
        "description": "Accompagnement en marketing digital, SEO, publicités",
        "revenus_potentiels": "3 000 - 12 000€/mois",
        "temps_objectif_5k": "4-8 mois",
        "capital_requis": "0 - 1 000€",
        "scalabilite": 3,
        "competences_requises": ["Marketing digital/SEO/Ads"],
        "competences_bonus": ["Rédaction/Copywriting", "Vente/Négociation"],
        "modele_revenu": "Prestations de service (freelance, consulting)",
        "type_client": "B2B - Entreprises/Professionnels",
        "lieu": ["100% à domicile/remote", "Nomade digital - depuis n'importe où"],
        "visibilite": ["Oui, je veux être le visage de mon business", "Oui, mais uniquement sur certains canaux"],
        "risque": 1,
        "avantages": ["Forte demande PME", "Revenus récurrents possibles", "Évolution agence"],
        "inconvenients": ["Concurrence forte", "Prouver ses résultats", "Clients exigeants"],
        "etapes_demarrage": ["Certifications Google/Meta", "Études de cas", "Prospection LinkedIn", "Audit gratuit"],
        "ressources": ["Google Skillshop", "HubSpot Academy", "Semrush"]
    },
    "freelance_copywriter": {
        "nom": "Copywriter/Rédacteur Web",
        "categorie": "Freelance",
        "description": "Rédaction persuasive, pages de vente, emails, contenus SEO",
        "revenus_potentiels": "2 000 - 10 000€/mois",
        "temps_objectif_5k": "6-12 mois",
        "capital_requis": "0 - 300€",
        "scalabilite": 2,
        "competences_requises": ["Rédaction/Copywriting"],
        "competences_bonus": ["Marketing digital/SEO/Ads"],
        "modele_revenu": "Prestations de service (freelance, consulting)",
        "type_client": "B2B - Entreprises/Professionnels",
        "lieu": ["100% à domicile/remote", "Nomade digital - depuis n'importe où"],
        "visibilite": ["Non - je veux un business anonyme/discret", "Modérément - je préfère rester en retrait"],
        "risque": 1,
        "avantages": ["Zéro investissement", "Travail partout", "Niche lucrative (pages de vente)"],
        "inconvenients": ["Tarifs bas au début", "Volume de travail", "Deadlines serrées"],
        "etapes_demarrage": ["Portfolio textes", "Niche rentable", "Malt/Redacteur.com", "Cold emailing"],
        "ressources": ["Redacteur.com", "Scribeur", "Copywriting courses"]
    },
    "freelance_video": {
        "nom": "Monteur Vidéo/Motion Designer",
        "categorie": "Freelance",
        "description": "Montage vidéo, motion design, animations pour créateurs et entreprises",
        "revenus_potentiels": "2 500 - 12 000€/mois",
        "temps_objectif_5k": "4-8 mois",
        "capital_requis": "1 000 - 3 000€",
        "scalabilite": 2,
        "competences_requises": ["Vidéo/Montage"],
        "competences_bonus": ["Design graphique/UI-UX", "Créativité/Innovation"],
        "modele_revenu": "Prestations de service (freelance, consulting)",
        "type_client": "Les deux me conviennent",
        "lieu": ["100% à domicile/remote", "Nomade digital - depuis n'importe où"],
        "visibilite": ["Non - je veux un business anonyme/discret"],
        "risque": 1,
        "avantages": ["Forte demande YouTubers", "Tarifs élevés motion", "Récurrence possible"],
        "inconvenients": ["PC puissant requis", "Fichiers lourds", "Révisions multiples"],
        "etapes_demarrage": ["Showreel portfolio", "Cibler YouTubers/agences", "Tarif au projet", "Fiverr Pro"],
        "ressources": ["Premiere Pro", "After Effects", "DaVinci Resolve"]
    },
    "freelance_va": {
        "nom": "Assistant Virtuel Premium",
        "categorie": "Freelance",
        "description": "Support administratif haut de gamme pour entrepreneurs",
        "revenus_potentiels": "2 000 - 6 000€/mois",
        "temps_objectif_5k": "6-12 mois",
        "capital_requis": "0 - 200€",
        "scalabilite": 2,
        "competences_requises": ["Organisation/Rigueur"],
        "competences_bonus": ["Gestion de projet", "Rédaction/Copywriting"],
        "modele_revenu": "Prestations de service (freelance, consulting)",
        "type_client": "B2B - Entreprises/Professionnels",
        "lieu": ["100% à domicile/remote"],
        "visibilite": ["Non - je veux un business anonyme/discret"],
        "risque": 1,
        "avantages": ["Démarrage immédiat", "Clients fidèles", "Évolution possible"],
        "inconvenients": ["Tarifs limités", "Disponibilité requise", "Tâches variées"],
        "etapes_demarrage": ["Définir services", "Cible entrepreneurs", "Belay/Time Etc", "Forfaits mensuels"],
        "ressources": ["Belay", "Time Etc", "Notion", "Calendly"]
    },
    "freelance_comptable": {
        "nom": "Comptable/Expert-comptable Indépendant",
        "categorie": "Freelance",
        "description": "Services comptables pour TPE/PME et indépendants",
        "revenus_potentiels": "4 000 - 15 000€/mois",
        "temps_objectif_5k": "3-6 mois",
        "capital_requis": "1 000 - 5 000€",
        "scalabilite": 3,
        "competences_requises": ["Comptabilité/Finance"],
        "competences_bonus": ["Vente/Négociation", "Organisation/Rigueur"],
        "modele_revenu": "Prestations de service (freelance, consulting)",
        "type_client": "B2B - Entreprises/Professionnels",
        "lieu": ["100% à domicile/remote", "Principalement à domicile avec déplacements occasionnels"],
        "visibilite": ["Modérément - je préfère rester en retrait"],
        "risque": 1,
        "avantages": ["Récurrence assurée", "Clients fidèles", "Expertise valorisée"],
        "inconvenients": ["Diplôme parfois requis", "Pics de charge", "Responsabilité"],
        "etapes_demarrage": ["Logiciel comptable", "Cibler freelances/TPE", "Forfaits clairs", "Réseau local"],
        "ressources": ["Pennylane", "Indy", "QuickBooks"]
    },

    # ============================================================
    # AGENCES
    # ============================================================
    "agence_digitale": {
        "nom": "Agence Digitale Full-Service",
        "categorie": "Agence",
        "description": "Agence proposant dev, design, marketing complet",
        "revenus_potentiels": "10 000 - 50 000€/mois",
        "temps_objectif_5k": "6-12 mois",
        "capital_requis": "2 000 - 10 000€",
        "scalabilite": 4,
        "competences_requises": ["Gestion de projet", "Vente/Négociation"],
        "competences_bonus": ["Développement web/mobile", "Marketing digital/SEO/Ads"],
        "modele_revenu": "Prestations de service (freelance, consulting)",
        "type_client": "B2B - Entreprises/Professionnels",
        "lieu": ["100% à domicile/remote", "Local commercial/Bureau"],
        "visibilite": ["Oui, je veux être le visage de mon business"],
        "risque": 2,
        "avantages": ["Très scalable", "Revenus récurrents", "Valorisation revente"],
        "inconvenients": ["Gestion équipe", "Trésorerie", "Cycle vente long"],
        "etapes_demarrage": ["Positionnement niche", "Réseau freelances", "Site vitrine", "Prospection active"],
        "ressources": ["Collective.work", "Notion", "ClickUp"]
    },
    "agence_seo": {
        "nom": "Agence SEO",
        "categorie": "Agence",
        "description": "Services de référencement naturel pour entreprises",
        "revenus_potentiels": "8 000 - 40 000€/mois",
        "temps_objectif_5k": "6-12 mois",
        "capital_requis": "1 000 - 5 000€",
        "scalabilite": 4,
        "competences_requises": ["Marketing digital/SEO/Ads"],
        "competences_bonus": ["Rédaction/Copywriting", "Développement web/mobile"],
        "modele_revenu": "Prestations de service (freelance, consulting)",
        "type_client": "B2B - Entreprises/Professionnels",
        "lieu": ["100% à domicile/remote"],
        "visibilite": ["Oui, mais uniquement sur certains canaux"],
        "risque": 2,
        "avantages": ["Revenus très récurrents", "Résultats mesurables", "Forte demande"],
        "inconvenients": ["Résultats longs", "Algorithmes changeants", "Concurrence"],
        "etapes_demarrage": ["Outils SEO pro", "Études de cas", "Forfaits mensuels", "Cibler PME locales"],
        "ressources": ["Ahrefs", "Semrush", "Screaming Frog"]
    },
    "agence_ads": {
        "nom": "Agence Publicité (Facebook/Google Ads)",
        "categorie": "Agence",
        "description": "Gestion de campagnes publicitaires pour clients",
        "revenus_potentiels": "8 000 - 50 000€/mois",
        "temps_objectif_5k": "4-8 mois",
        "capital_requis": "1 000 - 3 000€",
        "scalabilite": 4,
        "competences_requises": ["Marketing digital/SEO/Ads"],
        "competences_bonus": ["Rédaction/Copywriting", "Design graphique/UI-UX"],
        "modele_revenu": "Prestations de service (freelance, consulting)",
        "type_client": "B2B - Entreprises/Professionnels",
        "lieu": ["100% à domicile/remote", "Nomade digital - depuis n'importe où"],
        "visibilite": ["Oui, je veux être le visage de mon business"],
        "risque": 2,
        "avantages": ["Résultats rapides", "% du budget géré", "Très demandé e-commerce"],
        "inconvenients": ["Pression résultats", "Budgets fluctuants", "Apprentissage continu"],
        "etapes_demarrage": ["Certifications Meta/Google", "Cas clients", "Cibler e-commerce", "Pricing % ou fixe"],
        "ressources": ["Meta Blueprint", "Google Ads", "Triple Whale"]
    },
    "agence_smma": {
        "nom": "Agence Social Media (SMMA)",
        "categorie": "Agence",
        "description": "Gestion des réseaux sociaux pour entreprises",
        "revenus_potentiels": "5 000 - 30 000€/mois",
        "temps_objectif_5k": "4-8 mois",
        "capital_requis": "500 - 2 000€",
        "scalabilite": 4,
        "competences_requises": ["Marketing digital/SEO/Ads"],
        "competences_bonus": ["Design graphique/UI-UX", "Vidéo/Montage", "Rédaction/Copywriting"],
        "modele_revenu": "Prestations de service (freelance, consulting)",
        "type_client": "B2B - Entreprises/Professionnels",
        "lieu": ["100% à domicile/remote"],
        "visibilite": ["Oui, je veux être le visage de mon business"],
        "risque": 2,
        "avantages": ["Récurrence mensuelle", "Scalable", "Niches rentables"],
        "inconvenients": ["Création contenu intensive", "Clients exigeants", "Résultats attendus"],
        "etapes_demarrage": ["Choisir niche (resto, immo, fitness)", "Pack mensuel", "Cold outreach", "Cas études"],
        "ressources": ["Later", "Hootsuite", "Canva Pro"]
    },
    "agence_recrutement": {
        "nom": "Cabinet de Recrutement/Chasse de têtes",
        "categorie": "Agence",
        "description": "Recrutement pour entreprises, placement de candidats",
        "revenus_potentiels": "10 000 - 50 000€/mois",
        "temps_objectif_5k": "6-12 mois",
        "capital_requis": "2 000 - 10 000€",
        "scalabilite": 4,
        "competences_requises": ["Networking/Création de contacts", "Vente/Négociation"],
        "competences_bonus": ["Communication/Prise de parole"],
        "modele_revenu": "Prestations de service (freelance, consulting)",
        "type_client": "B2B - Entreprises/Professionnels",
        "lieu": ["100% à domicile/remote", "Principalement à domicile avec déplacements occasionnels"],
        "visibilite": ["Oui, je veux être le visage de mon business"],
        "risque": 2,
        "avantages": ["Commissions élevées (15-25% salaire)", "Pas de stock", "Relatonnel"],
        "inconvenients": ["Cycle long", "Marché concurrentiel", "Dépendance économie"],
        "etapes_demarrage": ["Niche sectorielle", "Réseau LinkedIn", "ATS simple", "Prospection entreprises"],
        "ressources": ["LinkedIn Recruiter", "Welcome to the Jungle", "Teamtailor"]
    },
    "agence_ia": {
        "nom": "Agence IA/Chatbots",
        "categorie": "Agence",
        "description": "Solutions IA personnalisées, chatbots, automatisation",
        "revenus_potentiels": "8 000 - 50 000€/mois",
        "temps_objectif_5k": "4-8 mois",
        "capital_requis": "1 000 - 5 000€",
        "scalabilite": 4,
        "competences_requises": ["Développement web/mobile"],
        "competences_bonus": ["Vente/Négociation", "Gestion de projet"],
        "modele_revenu": "Prestations de service (freelance, consulting)",
        "type_client": "B2B - Entreprises/Professionnels",
        "lieu": ["100% à domicile/remote"],
        "visibilite": ["Oui, je veux être le visage de mon business"],
        "risque": 2,
        "tendances": ["Intelligence Artificielle"],
        "avantages": ["Marché naissant", "Tarifs très élevés", "Positionnement expert"],
        "inconvenients": ["Compétences tech", "Techno évolutive", "Éducation marché"],
        "etapes_demarrage": ["Maîtriser APIs LLM", "Démos impressionnantes", "LinkedIn", "Cibler secteurs clés"],
        "ressources": ["OpenAI", "Anthropic", "Langchain", "Voiceflow"]
    },
    "agence_web": {
        "nom": "Agence Création de Sites Web",
        "categorie": "Agence",
        "description": "Création de sites vitrines et e-commerce pour PME",
        "revenus_potentiels": "6 000 - 25 000€/mois",
        "temps_objectif_5k": "4-8 mois",
        "capital_requis": "500 - 3 000€",
        "scalabilite": 3,
        "competences_requises": ["Développement web/mobile"],
        "competences_bonus": ["Design graphique/UI-UX", "Vente/Négociation"],
        "modele_revenu": "Prestations de service (freelance, consulting)",
        "type_client": "B2B - Entreprises/Professionnels",
        "lieu": ["100% à domicile/remote", "Principalement à domicile avec déplacements occasionnels"],
        "visibilite": ["Modérément - je préfère rester en retrait"],
        "risque": 2,
        "avantages": ["Demande locale forte", "Maintenance récurrente", "Upsell SEO/Ads"],
        "inconvenients": ["Concurrence Wix", "Clients non-tech", "Scope creep"],
        "etapes_demarrage": ["Stack WordPress/Webflow", "Portfolio 5 sites", "Cibler PME locales", "Pack tout-inclus"],
        "ressources": ["WordPress", "Webflow", "Elementor"]
    },

    # ============================================================
    # COACHING / FORMATION
    # ============================================================
    "formation_en_ligne": {
        "nom": "Formateur en Ligne",
        "categorie": "Formation",
        "description": "Création et vente de formations en ligne",
        "revenus_potentiels": "2 000 - 50 000€/mois",
        "temps_objectif_5k": "6-12 mois",
        "capital_requis": "500 - 3 000€",
        "scalabilite": 5,
        "competences_requises": ["Pédagogie/Transmission"],
        "competences_bonus": ["Marketing digital/SEO/Ads", "Vidéo/Montage"],
        "modele_revenu": "Vente de produits digitaux (formations, ebooks)",
        "type_client": "B2C - Particuliers",
        "lieu": ["100% à domicile/remote", "Nomade digital - depuis n'importe où"],
        "visibilite": ["Oui, je veux être le visage de mon business"],
        "risque": 2,
        "avantages": ["Revenus passifs", "Très scalable", "Impact positif"],
        "inconvenients": ["Audience à construire", "Marché saturé", "Expertise requise"],
        "etapes_demarrage": ["Expertise monétisable", "Contenu gratuit", "Liste email", "Première formation"],
        "ressources": ["Podia", "Teachable", "Systeme.io"]
    },
    "coaching_business": {
        "nom": "Coach Business/Entrepreneur",
        "categorie": "Formation",
        "description": "Accompagnement entrepreneurs et dirigeants",
        "revenus_potentiels": "5 000 - 30 000€/mois",
        "temps_objectif_5k": "3-6 mois",
        "capital_requis": "0 - 2 000€",
        "scalabilite": 3,
        "competences_requises": ["Communication/Prise de parole", "Écoute et empathie"],
        "competences_bonus": ["Pédagogie/Transmission", "Vente/Négociation"],
        "modele_revenu": "Prestations de service (freelance, consulting)",
        "type_client": "B2B - Entreprises/Professionnels",
        "lieu": ["100% à domicile/remote"],
        "visibilite": ["Oui, je veux être le visage de mon business"],
        "risque": 1,
        "avantages": ["Tarifs élevés (500-2000€/mois)", "Impact réel", "Relatonnel enrichissant"],
        "inconvenients": ["Crédibilité à prouver", "Énergie intensive", "Temps limité"],
        "etapes_demarrage": ["Niche claire", "Offre signature", "Témoignages", "LinkedIn personal branding"],
        "ressources": ["Calendly", "Zoom", "Notion"]
    },
    "coaching_vie": {
        "nom": "Coach de Vie/Développement Personnel",
        "categorie": "Formation",
        "description": "Accompagnement individuel sur objectifs de vie",
        "revenus_potentiels": "3 000 - 15 000€/mois",
        "temps_objectif_5k": "6-12 mois",
        "capital_requis": "500 - 3 000€",
        "scalabilite": 3,
        "competences_requises": ["Écoute et empathie", "Communication/Prise de parole"],
        "competences_bonus": ["Pédagogie/Transmission"],
        "modele_revenu": "Prestations de service (freelance, consulting)",
        "type_client": "B2C - Particuliers",
        "lieu": ["100% à domicile/remote", "Principalement à domicile avec déplacements occasionnels"],
        "visibilite": ["Oui, je veux être le visage de mon business"],
        "risque": 1,
        "avantages": ["Sens du travail", "Clientèle fidèle", "Bouche-à-oreille"],
        "inconvenients": ["Certification souvent attendue", "Marché saturé", "Émotionnel"],
        "etapes_demarrage": ["Certification coaching", "Niche spécifique", "Présence Instagram", "Séance découverte"],
        "ressources": ["ICF", "International Coach Academy"]
    },
    "coaching_sport": {
        "nom": "Coach Sportif/Personal Trainer",
        "categorie": "Formation",
        "description": "Coaching fitness en ligne ou présentiel",
        "revenus_potentiels": "3 000 - 15 000€/mois",
        "temps_objectif_5k": "4-8 mois",
        "capital_requis": "500 - 3 000€",
        "scalabilite": 3,
        "competences_requises": ["Santé/Bien-être"],
        "competences_bonus": ["Marketing digital/SEO/Ads", "Vidéo/Montage"],
        "modele_revenu": "Prestations de service (freelance, consulting)",
        "type_client": "B2C - Particuliers",
        "lieu": ["Principalement à domicile avec déplacements occasionnels", "100% à domicile/remote"],
        "visibilite": ["Oui, je veux être le visage de mon business"],
        "risque": 1,
        "passions": ["Santé/Fitness/Bien-être", "Sport"],
        "avantages": ["Passion = travail", "Programmes en ligne scalables", "Transformation visible"],
        "inconvenients": ["Diplôme requis", "Horaires variables", "Concurrence apps"],
        "etapes_demarrage": ["Certification BPJEPS/autre", "Instagram physique", "Programmes PDF", "Coaching en ligne"],
        "ressources": ["Trainerize", "TrueCoach", "Instagram"]
    },
    "coaching_carriere": {
        "nom": "Coach Carrière/Reconversion",
        "categorie": "Formation",
        "description": "Accompagnement transitions professionnelles",
        "revenus_potentiels": "4 000 - 12 000€/mois",
        "temps_objectif_5k": "4-8 mois",
        "capital_requis": "0 - 1 500€",
        "scalabilite": 3,
        "competences_requises": ["Écoute et empathie", "Communication/Prise de parole"],
        "competences_bonus": ["Networking/Création de contacts"],
        "modele_revenu": "Prestations de service (freelance, consulting)",
        "type_client": "B2C - Particuliers",
        "lieu": ["100% à domicile/remote"],
        "visibilite": ["Oui, je veux être le visage de mon business"],
        "risque": 1,
        "avantages": ["Forte demande post-covid", "Transformations concrètes", "CPF possible"],
        "inconvenients": ["Certification attendue", "Processus long", "Émotionnel"],
        "etapes_demarrage": ["Certification coach", "Cible reconversion", "LinkedIn", "Partenariats RH"],
        "ressources": ["LinkedIn", "Certifications coaching"]
    },
    "mentor_tech": {
        "nom": "Mentor/Tuteur Tech",
        "categorie": "Formation",
        "description": "Mentorat développeurs juniors et reconversions",
        "revenus_potentiels": "2 000 - 8 000€/mois",
        "temps_objectif_5k": "6-12 mois",
        "capital_requis": "0 - 500€",
        "scalabilite": 3,
        "competences_requises": ["Développement web/mobile", "Pédagogie/Transmission"],
        "competences_bonus": [],
        "modele_revenu": "Prestations de service (freelance, consulting)",
        "type_client": "B2C - Particuliers",
        "lieu": ["100% à domicile/remote"],
        "visibilite": ["Oui, mais uniquement sur certains canaux"],
        "risque": 1,
        "avantages": ["Sessions courtes", "Impact réel", "Plateformes existantes"],
        "inconvenients": ["Tarifs moyens", "Préparation cours", "Disponibilité horaires"],
        "etapes_demarrage": ["Profil Codementor/Mentorcruise", "Spécialité tech", "Tarif horaire", "Contenu gratuit"],
        "ressources": ["Codementor", "MentorCruise", "ADPList"]
    },

    # ============================================================
    # E-COMMERCE
    # ============================================================
    "ecommerce_marque": {
        "nom": "E-commerce Marque Propre (DTC)",
        "categorie": "E-commerce",
        "description": "Création et vente de produits sous sa propre marque",
        "revenus_potentiels": "5 000 - 100 000€/mois",
        "temps_objectif_5k": "12-24 mois",
        "capital_requis": "5 000 - 30 000€",
        "scalabilite": 5,
        "competences_requises": ["Marketing digital/SEO/Ads"],
        "competences_bonus": ["Design graphique/UI-UX", "Gestion de projet"],
        "modele_revenu": "Vente de produits physiques",
        "type_client": "B2C - Particuliers",
        "lieu": ["100% à domicile/remote", "Local commercial/Bureau"],
        "visibilite": ["Non - je veux un business anonyme/discret", "Modérément - je préfère rester en retrait"],
        "risque": 3,
        "avantages": ["Asset revendable", "Marges élevées", "Marque valorisable"],
        "inconvenients": ["Capital important", "Stock/logistique", "Concurrence"],
        "etapes_demarrage": ["Étude de marché", "Fournisseur Alibaba", "Shopify", "Ads Facebook/Google"],
        "ressources": ["Shopify", "Alibaba", "Klaviyo"]
    },
    "amazon_fba": {
        "nom": "Amazon FBA",
        "categorie": "E-commerce",
        "description": "Vente sur Amazon avec logistique gérée",
        "revenus_potentiels": "3 000 - 50 000€/mois",
        "temps_objectif_5k": "12-18 mois",
        "capital_requis": "5 000 - 20 000€",
        "scalabilite": 4,
        "competences_requises": [],
        "competences_bonus": ["Marketing digital/SEO/Ads"],
        "modele_revenu": "Vente de produits physiques",
        "type_client": "B2C - Particuliers",
        "lieu": ["100% à domicile/remote"],
        "visibilite": ["Non - je veux un business anonyme/discret"],
        "risque": 3,
        "avantages": ["Logistique Amazon", "Millions de clients", "Système éprouvé"],
        "inconvenients": ["Dépendance Amazon", "Frais élevés", "Concurrence féroce"],
        "etapes_demarrage": ["Formation FBA", "Jungle Scout recherche", "Fournisseur", "Optimiser listing"],
        "ressources": ["Jungle Scout", "Helium 10", "Amazon Seller Central"]
    },
    "dropshipping": {
        "nom": "Dropshipping",
        "categorie": "E-commerce",
        "description": "Vente sans stock, expédition fournisseur",
        "revenus_potentiels": "1 000 - 20 000€/mois",
        "temps_objectif_5k": "6-12 mois",
        "capital_requis": "500 - 3 000€",
        "scalabilite": 3,
        "competences_requises": ["Marketing digital/SEO/Ads"],
        "competences_bonus": ["Design graphique/UI-UX"],
        "modele_revenu": "Vente de produits physiques",
        "type_client": "B2C - Particuliers",
        "lieu": ["100% à domicile/remote", "Nomade digital - depuis n'importe où"],
        "visibilite": ["Non - je veux un business anonyme/discret"],
        "risque": 2,
        "avantages": ["Peu de capital", "Pas de stock", "Test rapide"],
        "inconvenients": ["Marges faibles", "Qualité aléatoire", "SAV difficile"],
        "etapes_demarrage": ["Niche rentable", "Shopify", "Produits gagnants", "Publicités"],
        "ressources": ["Shopify", "DSers", "CJ Dropshipping"]
    },
    "print_on_demand": {
        "nom": "Print on Demand",
        "categorie": "E-commerce",
        "description": "Vente de produits personnalisés (t-shirts, mugs, etc.)",
        "revenus_potentiels": "1 000 - 15 000€/mois",
        "temps_objectif_5k": "12-18 mois",
        "capital_requis": "200 - 1 000€",
        "scalabilite": 4,
        "competences_requises": ["Design graphique/UI-UX"],
        "competences_bonus": ["Marketing digital/SEO/Ads"],
        "modele_revenu": "Vente de produits physiques",
        "type_client": "B2C - Particuliers",
        "lieu": ["100% à domicile/remote", "Nomade digital - depuis n'importe où"],
        "visibilite": ["Non - je veux un business anonyme/discret"],
        "risque": 1,
        "avantages": ["Zéro stock", "Créativité", "Niches infinies"],
        "inconvenients": ["Marges moyennes", "Concurrence designs", "Délais livraison"],
        "etapes_demarrage": ["Niche passionnée", "Designs originaux", "Printful/Printify", "Etsy ou Shopify"],
        "ressources": ["Printful", "Printify", "Etsy", "Redbubble"]
    },
    "vente_etsy": {
        "nom": "Boutique Etsy",
        "categorie": "E-commerce",
        "description": "Vente d'articles faits main ou vintage",
        "revenus_potentiels": "1 000 - 10 000€/mois",
        "temps_objectif_5k": "12-24 mois",
        "capital_requis": "200 - 2 000€",
        "scalabilite": 3,
        "competences_requises": ["Artisanat/Manuel"],
        "competences_bonus": ["Design graphique/UI-UX", "Marketing digital/SEO/Ads"],
        "modele_revenu": "Vente de produits physiques",
        "type_client": "B2C - Particuliers",
        "lieu": ["100% à domicile/remote"],
        "visibilite": ["Non - je veux un business anonyme/discret"],
        "risque": 2,
        "passions": ["Art/Créativité"],
        "avantages": ["Trafic gratuit Etsy", "Niche créative", "Communauté"],
        "inconvenients": ["Frais Etsy", "Création chronophage", "Saisonnalité"],
        "etapes_demarrage": ["Produit unique", "Photos pro", "SEO Etsy", "Reviews"],
        "ressources": ["Etsy", "eRank", "Marmalead"]
    },
    "revente_occasions": {
        "nom": "Revente/Flipping (occasions, vintage)",
        "categorie": "E-commerce",
        "description": "Achat-revente d'objets à profit",
        "revenus_potentiels": "2 000 - 10 000€/mois",
        "temps_objectif_5k": "6-12 mois",
        "capital_requis": "1 000 - 5 000€",
        "scalabilite": 3,
        "competences_requises": ["Vente/Négociation"],
        "competences_bonus": [],
        "modele_revenu": "Vente de produits physiques",
        "type_client": "B2C - Particuliers",
        "lieu": ["Principalement à domicile avec déplacements occasionnels"],
        "visibilite": ["Non - je veux un business anonyme/discret"],
        "risque": 2,
        "tendances": ["Seconde main/Économie circulaire"],
        "avantages": ["Démarrage rapide", "Marge sur expertise", "Chasse aux bonnes affaires"],
        "inconvenients": ["Temps sourcing", "Stockage", "Incertitude"],
        "etapes_demarrage": ["Niche (sneakers, meubles, tech)", "Sourcing brocantes/LBC", "Vinted/eBay", "Prix marché"],
        "ressources": ["Vinted", "eBay", "Leboncoin", "StockX"]
    },
    "ecommerce_abonnement": {
        "nom": "Box par Abonnement",
        "categorie": "E-commerce",
        "description": "Box mensuelle thématique livrée aux abonnés",
        "revenus_potentiels": "3 000 - 30 000€/mois",
        "temps_objectif_5k": "12-18 mois",
        "capital_requis": "3 000 - 15 000€",
        "scalabilite": 4,
        "competences_requises": ["Marketing digital/SEO/Ads"],
        "competences_bonus": ["Gestion de projet", "Négociation"],
        "modele_revenu": "Abonnements/Revenus récurrents (SaaS, membership)",
        "type_client": "B2C - Particuliers",
        "lieu": ["100% à domicile/remote", "Local commercial/Bureau"],
        "visibilite": ["Oui, mais uniquement sur certains canaux"],
        "risque": 3,
        "avantages": ["Revenus récurrents prévisibles", "Fidélisation", "Partenariats marques"],
        "inconvenients": ["Logistique complexe", "Churn", "Capital stock"],
        "etapes_demarrage": ["Niche passionnée", "Fournisseurs", "Plateforme abo", "Marketing influenceurs"],
        "ressources": ["Cratejoy", "Subbly", "Recharge"]
    },

    # ============================================================
    # SAAS / TECH
    # ============================================================
    "saas_micro": {
        "nom": "Micro-SaaS",
        "categorie": "Tech",
        "description": "Petit logiciel résolvant un problème spécifique",
        "revenus_potentiels": "2 000 - 30 000€/mois",
        "temps_objectif_5k": "12-24 mois",
        "capital_requis": "0 - 5 000€",
        "scalabilite": 5,
        "competences_requises": ["Développement web/mobile"],
        "competences_bonus": ["Marketing digital/SEO/Ads", "Design graphique/UI-UX"],
        "modele_revenu": "Abonnements/Revenus récurrents (SaaS, membership)",
        "type_client": "B2B - Entreprises/Professionnels",
        "lieu": ["100% à domicile/remote", "Nomade digital - depuis n'importe où"],
        "visibilite": ["Non - je veux un business anonyme/discret"],
        "risque": 3,
        "tendances": ["Intelligence Artificielle", "Automatisation/No-code"],
        "avantages": ["Revenus récurrents", "Très scalable", "Asset valorisé"],
        "inconvenients": ["Long à développer", "Support client", "Concurrence"],
        "etapes_demarrage": ["Problème récurrent", "Valider prospects", "MVP rapide", "Itérer"],
        "ressources": ["Indie Hackers", "MicroConf", "Stripe"]
    },
    "saas_nocode": {
        "nom": "SaaS/App No-Code",
        "categorie": "Tech",
        "description": "Application créée avec outils no-code",
        "revenus_potentiels": "1 000 - 15 000€/mois",
        "temps_objectif_5k": "12-18 mois",
        "capital_requis": "500 - 2 000€",
        "scalabilite": 4,
        "competences_requises": [],
        "competences_bonus": ["Design graphique/UI-UX", "Marketing digital/SEO/Ads"],
        "modele_revenu": "Abonnements/Revenus récurrents (SaaS, membership)",
        "type_client": "Les deux me conviennent",
        "lieu": ["100% à domicile/remote", "Nomade digital - depuis n'importe où"],
        "visibilite": ["Modérément - je préfère rester en retrait"],
        "risque": 2,
        "tendances": ["Automatisation/No-code"],
        "avantages": ["Pas besoin de coder", "Lancement rapide", "Coût faible"],
        "inconvenients": ["Limitations techniques", "Coûts outils", "Moins de contrôle"],
        "etapes_demarrage": ["Apprendre Bubble/Webflow", "Problème niche", "MVP", "Itérer"],
        "ressources": ["Bubble.io", "Webflow", "Glide", "Airtable"]
    },
    "app_mobile": {
        "nom": "Application Mobile",
        "categorie": "Tech",
        "description": "Développement et monétisation d'apps mobiles",
        "revenus_potentiels": "1 000 - 50 000€/mois",
        "temps_objectif_5k": "12-24 mois",
        "capital_requis": "2 000 - 20 000€",
        "scalabilite": 5,
        "competences_requises": ["Développement web/mobile"],
        "competences_bonus": ["Design graphique/UI-UX", "Marketing digital/SEO/Ads"],
        "modele_revenu": "Abonnements/Revenus récurrents (SaaS, membership)",
        "type_client": "B2C - Particuliers",
        "lieu": ["100% à domicile/remote"],
        "visibilite": ["Non - je veux un business anonyme/discret"],
        "risque": 3,
        "avantages": ["Marché énorme", "Revenus passifs", "Scalabilité infinie"],
        "inconvenients": ["Concurrence App Store", "ASO complexe", "Maintenance"],
        "etapes_demarrage": ["Idée validée", "MVP Flutter/React Native", "Beta testeurs", "ASO"],
        "ressources": ["Flutter", "React Native", "RevenueCat"]
    },
    "plugin_extension": {
        "nom": "Plugin/Extension (WordPress, Chrome, etc.)",
        "categorie": "Tech",
        "description": "Développement de plugins ou extensions",
        "revenus_potentiels": "1 000 - 20 000€/mois",
        "temps_objectif_5k": "12-18 mois",
        "capital_requis": "0 - 1 000€",
        "scalabilite": 5,
        "competences_requises": ["Développement web/mobile"],
        "competences_bonus": [],
        "modele_revenu": "Vente de produits digitaux (formations, ebooks)",
        "type_client": "Les deux me conviennent",
        "lieu": ["100% à domicile/remote"],
        "visibilite": ["Non - je veux un business anonyme/discret"],
        "risque": 2,
        "avantages": ["Écosystème existant", "Distribution gratuite", "Revenus passifs"],
        "inconvenients": ["Dépendance plateforme", "Support utilisateurs", "Mises à jour"],
        "etapes_demarrage": ["Problème utilisateurs", "Plugin MVP", "Freemium", "Support réactif"],
        "ressources": ["WordPress.org", "Chrome Web Store", "Gumroad"]
    },
    "template_themes": {
        "nom": "Vente de Templates/Thèmes",
        "categorie": "Tech",
        "description": "Création et vente de templates Notion, Figma, WordPress...",
        "revenus_potentiels": "1 000 - 15 000€/mois",
        "temps_objectif_5k": "12-18 mois",
        "capital_requis": "0 - 500€",
        "scalabilite": 5,
        "competences_requises": ["Design graphique/UI-UX"],
        "competences_bonus": ["Développement web/mobile"],
        "modele_revenu": "Vente de produits digitaux (formations, ebooks)",
        "type_client": "Les deux me conviennent",
        "lieu": ["100% à domicile/remote", "Nomade digital - depuis n'importe où"],
        "visibilite": ["Non - je veux un business anonyme/discret"],
        "risque": 1,
        "avantages": ["Revenus passifs", "Création unique", "Marketplaces existantes"],
        "inconvenients": ["Concurrence", "Support", "Mises à jour"],
        "etapes_demarrage": ["Niche template", "Design pro", "Gumroad/ThemeForest", "Twitter marketing"],
        "ressources": ["Gumroad", "ThemeForest", "Notion", "Figma Community"]
    },
    "automatisation_ia": {
        "nom": "Services Automatisation/IA",
        "categorie": "Tech",
        "description": "Automatisation de process avec IA et no-code",
        "revenus_potentiels": "5 000 - 25 000€/mois",
        "temps_objectif_5k": "3-6 mois",
        "capital_requis": "0 - 1 000€",
        "scalabilite": 4,
        "competences_requises": [],
        "competences_bonus": ["Développement web/mobile", "Résolution de problèmes"],
        "modele_revenu": "Prestations de service (freelance, consulting)",
        "type_client": "B2B - Entreprises/Professionnels",
        "lieu": ["100% à domicile/remote", "Nomade digital - depuis n'importe où"],
        "visibilite": ["Oui, mais uniquement sur certains canaux"],
        "risque": 1,
        "tendances": ["Intelligence Artificielle", "Automatisation/No-code"],
        "avantages": ["Marché en explosion", "Tarifs élevés", "Forte demande"],
        "inconvenients": ["Évolution rapide", "Formation continue", "Éducation marché"],
        "etapes_demarrage": ["Former Make/Zapier/n8n + IA", "Cas études", "Cibler PME", "Audit gratuit"],
        "ressources": ["Make.com", "Zapier", "n8n", "OpenAI API"]
    },

    # ============================================================
    # CONTENU / MÉDIA
    # ============================================================
    "youtube": {
        "nom": "YouTuber",
        "categorie": "Contenu",
        "description": "Création de contenu vidéo monétisé",
        "revenus_potentiels": "1 000 - 50 000€/mois",
        "temps_objectif_5k": "18-36 mois",
        "capital_requis": "1 000 - 5 000€",
        "scalabilite": 4,
        "competences_requises": ["Vidéo/Montage", "Communication/Prise de parole"],
        "competences_bonus": ["Marketing digital/SEO/Ads", "Créativité/Innovation"],
        "modele_revenu": "Publicité/Contenu sponsorisé",
        "type_client": "B2C - Particuliers",
        "lieu": ["100% à domicile/remote", "Nomade digital - depuis n'importe où"],
        "visibilite": ["Oui, je veux être le visage de mon business"],
        "risque": 3,
        "avantages": ["Revenus passifs long terme", "Opportunités multiples", "Personal brand"],
        "inconvenients": ["Très long à construire", "Algorithme imprévisible", "Burnout créatif"],
        "etapes_demarrage": ["Niche rentable", "Matériel correct", "Régularité", "SEO YouTube"],
        "ressources": ["TubeBuddy", "VidIQ", "Canva"]
    },
    "podcast": {
        "nom": "Podcasteur",
        "categorie": "Contenu",
        "description": "Création de podcast monétisé",
        "revenus_potentiels": "500 - 20 000€/mois",
        "temps_objectif_5k": "18-36 mois",
        "capital_requis": "300 - 2 000€",
        "scalabilite": 3,
        "competences_requises": ["Communication/Prise de parole"],
        "competences_bonus": ["Networking/Création de contacts", "Rédaction/Copywriting"],
        "modele_revenu": "Publicité/Contenu sponsorisé",
        "type_client": "B2C - Particuliers",
        "lieu": ["100% à domicile/remote"],
        "visibilite": ["Oui, je veux être le visage de mon business"],
        "risque": 2,
        "avantages": ["Moins concurrentiel que YouTube", "Audience fidèle", "Networking"],
        "inconvenients": ["Monétisation plus difficile", "Croissance lente", "Régularité"],
        "etapes_demarrage": ["Concept différenciant", "Micro correct", "Régularité", "Invités"],
        "ressources": ["Riverside.fm", "Descript", "Anchor"]
    },
    "newsletter_payante": {
        "nom": "Newsletter Payante",
        "categorie": "Contenu",
        "description": "Newsletter premium par abonnement",
        "revenus_potentiels": "1 000 - 30 000€/mois",
        "temps_objectif_5k": "12-24 mois",
        "capital_requis": "0 - 500€",
        "scalabilite": 4,
        "competences_requises": ["Rédaction/Copywriting"],
        "competences_bonus": ["Marketing digital/SEO/Ads", "Networking/Création de contacts"],
        "modele_revenu": "Abonnements/Revenus récurrents (SaaS, membership)",
        "type_client": "Les deux me conviennent",
        "lieu": ["100% à domicile/remote", "Nomade digital - depuis n'importe où"],
        "visibilite": ["Oui, je veux être le visage de mon business"],
        "risque": 2,
        "avantages": ["Faible investissement", "Revenus récurrents", "Relation directe"],
        "inconvenients": ["Audience à construire", "Rythme intense", "Churn"],
        "etapes_demarrage": ["Angle unique", "Version gratuite", "Audience", "Offre payante"],
        "ressources": ["Substack", "Beehiiv", "ConvertKit"]
    },
    "newsletter_sponsorisee": {
        "nom": "Newsletter Sponsorisée",
        "categorie": "Contenu",
        "description": "Newsletter gratuite monétisée par sponsors",
        "revenus_potentiels": "2 000 - 50 000€/mois",
        "temps_objectif_5k": "12-24 mois",
        "capital_requis": "0 - 500€",
        "scalabilite": 4,
        "competences_requises": ["Rédaction/Copywriting"],
        "competences_bonus": ["Marketing digital/SEO/Ads", "Vente/Négociation"],
        "modele_revenu": "Publicité/Contenu sponsorisé",
        "type_client": "B2B - Entreprises/Professionnels",
        "lieu": ["100% à domicile/remote", "Nomade digital - depuis n'importe où"],
        "visibilite": ["Oui, je veux être le visage de mon business"],
        "risque": 2,
        "avantages": ["Gratuit = croissance rapide", "CPM élevés B2B", "Asset vendable"],
        "inconvenients": ["Volume abonnés requis", "Prospection sponsors", "Qualité constante"],
        "etapes_demarrage": ["Niche B2B rentable", "Croissance rapide", "10k+ abonnés", "Démarcher sponsors"],
        "ressources": ["Beehiiv", "Sparkloop", "Swapstack"]
    },
    "blogging_seo": {
        "nom": "Blogging SEO/Sites de Niche",
        "categorie": "Contenu",
        "description": "Sites de contenu monétisés par affiliation/pubs",
        "revenus_potentiels": "1 000 - 30 000€/mois",
        "temps_objectif_5k": "18-36 mois",
        "capital_requis": "500 - 3 000€",
        "scalabilite": 4,
        "competences_requises": ["Rédaction/Copywriting", "Marketing digital/SEO/Ads"],
        "competences_bonus": [],
        "modele_revenu": "Affiliation/Commission",
        "type_client": "Pas de contact client direct (produits automatisés)",
        "lieu": ["100% à domicile/remote", "Nomade digital - depuis n'importe où"],
        "visibilite": ["Non - je veux un business anonyme/discret"],
        "risque": 2,
        "avantages": ["Revenus passifs", "Asset vendable", "Scalable avec rédacteurs"],
        "inconvenients": ["SEO long", "Google updates", "Patience requise"],
        "etapes_demarrage": ["Niche rentable", "Recherche mots-clés", "Contenu qualité", "Backlinks"],
        "ressources": ["Ahrefs", "Semrush", "Mediavine", "Ezoic"]
    },
    "affiliation": {
        "nom": "Marketing d'Affiliation",
        "categorie": "Contenu",
        "description": "Promotion de produits contre commission",
        "revenus_potentiels": "1 000 - 30 000€/mois",
        "temps_objectif_5k": "12-24 mois",
        "capital_requis": "500 - 2 000€",
        "scalabilite": 4,
        "competences_requises": ["Marketing digital/SEO/Ads", "Rédaction/Copywriting"],
        "competences_bonus": [],
        "modele_revenu": "Affiliation/Commission",
        "type_client": "B2C - Particuliers",
        "lieu": ["100% à domicile/remote", "Nomade digital - depuis n'importe où"],
        "visibilite": ["Non - je veux un business anonyme/discret"],
        "risque": 2,
        "avantages": ["Pas de produit", "Revenus passifs", "Diversification"],
        "inconvenients": ["Dépendance programmes", "SEO long", "Commissions variables"],
        "etapes_demarrage": ["Niche rentable", "Site contenu", "SEO", "Programmes affiliation"],
        "ressources": ["Ahrefs", "Amazon Associates", "Awin", "CJ"]
    },
    "influenceur_instagram": {
        "nom": "Influenceur Instagram/TikTok",
        "categorie": "Contenu",
        "description": "Création de contenu et partenariats marques",
        "revenus_potentiels": "1 000 - 50 000€/mois",
        "temps_objectif_5k": "12-24 mois",
        "capital_requis": "500 - 3 000€",
        "scalabilite": 3,
        "competences_requises": ["Créativité/Innovation"],
        "competences_bonus": ["Vidéo/Montage", "Communication/Prise de parole"],
        "modele_revenu": "Publicité/Contenu sponsorisé",
        "type_client": "B2B - Entreprises/Professionnels",
        "lieu": ["100% à domicile/remote", "Nomade digital - depuis n'importe où"],
        "visibilite": ["Oui, je veux être le visage de mon business"],
        "risque": 3,
        "avantages": ["Partenariats lucratifs", "Diversification revenus", "Personal brand"],
        "inconvenients": ["Algorithmes changeants", "Pression constante", "Burn-out"],
        "etapes_demarrage": ["Niche passion", "Régularité", "Engagement communauté", "Média kit"],
        "ressources": ["Later", "Canva", "Influence.co"]
    },
    "createur_ugc": {
        "nom": "Créateur UGC (User Generated Content)",
        "categorie": "Contenu",
        "description": "Création de contenu publicitaire pour marques",
        "revenus_potentiels": "2 000 - 15 000€/mois",
        "temps_objectif_5k": "3-8 mois",
        "capital_requis": "500 - 2 000€",
        "scalabilite": 2,
        "competences_requises": ["Vidéo/Montage"],
        "competences_bonus": ["Communication/Prise de parole", "Créativité/Innovation"],
        "modele_revenu": "Prestations de service (freelance, consulting)",
        "type_client": "B2B - Entreprises/Professionnels",
        "lieu": ["100% à domicile/remote"],
        "visibilite": ["Oui, mais uniquement sur certains canaux"],
        "risque": 1,
        "tendances": ["Économie des créateurs"],
        "avantages": ["Pas besoin d'audience", "Demande explosive", "Revenus rapides"],
        "inconvenients": ["Production intensive", "Pas de revenus passifs", "Tendances changeantes"],
        "etapes_demarrage": ["Portfolio UGC", "Équipement smartphone", "Plateformes UGC", "Prospection marques"],
        "ressources": ["Billo", "Trend.io", "Insense"]
    },

    # ============================================================
    # IMMOBILIER
    # ============================================================
    "immobilier_location": {
        "nom": "Investissement Locatif Classique",
        "categorie": "Immobilier",
        "description": "Achat et mise en location de biens",
        "revenus_potentiels": "500 - 5 000€/mois (par bien)",
        "temps_objectif_5k": "24-48 mois",
        "capital_requis": "20 000 - 100 000€",
        "scalabilite": 4,
        "competences_requises": ["Immobilier"],
        "competences_bonus": ["Négociation", "Comptabilité/Finance"],
        "modele_revenu": "Abonnements/Revenus récurrents (SaaS, membership)",
        "type_client": "B2C - Particuliers",
        "lieu": ["Principalement à domicile avec déplacements occasionnels"],
        "visibilite": ["Non - je veux un business anonyme/discret"],
        "risque": 3,
        "passions": ["Immobilier"],
        "avantages": ["Revenus passifs", "Patrimoine", "Effet de levier"],
        "inconvenients": ["Capital important", "Gestion locative", "Impayés"],
        "etapes_demarrage": ["Formation immo", "Stratégie LMNP/coloc", "Bien rentable", "Financement"],
        "ressources": ["MeilleursAgents", "SeLoger"]
    },
    "immobilier_lcd": {
        "nom": "Location Courte Durée (Airbnb)",
        "categorie": "Immobilier",
        "description": "Location saisonnière type Airbnb",
        "revenus_potentiels": "1 000 - 8 000€/mois (par bien)",
        "temps_objectif_5k": "12-24 mois",
        "capital_requis": "15 000 - 80 000€",
        "scalabilite": 3,
        "competences_requises": ["Immobilier", "Organisation/Rigueur"],
        "competences_bonus": [],
        "modele_revenu": "Abonnements/Revenus récurrents (SaaS, membership)",
        "type_client": "B2C - Particuliers",
        "lieu": ["Principalement à domicile avec déplacements occasionnels"],
        "visibilite": ["Non - je veux un business anonyme/discret"],
        "risque": 3,
        "passions": ["Immobilier", "Voyage/Tourisme"],
        "avantages": ["Revenus supérieurs location classique", "Flexibilité", "Usage perso possible"],
        "inconvenients": ["Gestion intensive", "Réglementation", "Saisonnalité"],
        "etapes_demarrage": ["Zone touristique", "Bien adapté LCD", "Aménagement", "Annonce optimisée"],
        "ressources": ["Airbnb", "Booking", "PriceLabs"]
    },
    "conciergerie_airbnb": {
        "nom": "Conciergerie Airbnb",
        "categorie": "Immobilier",
        "description": "Gestion de LCD pour propriétaires",
        "revenus_potentiels": "2 000 - 15 000€/mois",
        "temps_objectif_5k": "6-12 mois",
        "capital_requis": "1 000 - 5 000€",
        "scalabilite": 3,
        "competences_requises": ["Organisation/Rigueur"],
        "competences_bonus": ["Négociation", "Networking/Création de contacts"],
        "modele_revenu": "Prestations de service (freelance, consulting)",
        "type_client": "B2B - Entreprises/Professionnels",
        "lieu": ["Sur le terrain/Chez les clients", "Principalement à domicile avec déplacements occasionnels"],
        "visibilite": ["Modérément - je préfère rester en retrait"],
        "risque": 2,
        "passions": ["Immobilier"],
        "avantages": ["Pas d'achat immobilier", "Récurrence", "Scalable"],
        "inconvenients": ["Disponibilité 7j/7", "Équipe ménage", "Saisonnalité"],
        "etapes_demarrage": ["Étude marché local", "Offre services", "Démarcher propriétaires", "Équipe"],
        "ressources": ["Lodgify", "Guesty", "Hostaway"]
    },
    "immobilier_colocation": {
        "nom": "Colocation/Coliving",
        "categorie": "Immobilier",
        "description": "Location en colocation pour maximiser rendement",
        "revenus_potentiels": "1 500 - 6 000€/mois (par bien)",
        "temps_objectif_5k": "18-36 mois",
        "capital_requis": "20 000 - 80 000€",
        "scalabilite": 3,
        "competences_requises": ["Immobilier"],
        "competences_bonus": ["Organisation/Rigueur"],
        "modele_revenu": "Abonnements/Revenus récurrents (SaaS, membership)",
        "type_client": "B2C - Particuliers",
        "lieu": ["Principalement à domicile avec déplacements occasionnels"],
        "visibilite": ["Non - je veux un business anonyme/discret"],
        "risque": 3,
        "passions": ["Immobilier"],
        "avantages": ["Rendement supérieur", "Turnover géré", "Marché étudiant"],
        "inconvenients": ["Gestion locataires", "Travaux aménagement", "Rotation"],
        "etapes_demarrage": ["Ville étudiante", "Grand appartement", "Aménagement chambres", "Gestion turnover"],
        "ressources": ["Appartager", "La Carte des Colocs"]
    },
    "marchand_biens": {
        "nom": "Marchand de Biens",
        "categorie": "Immobilier",
        "description": "Achat, rénovation, revente de biens",
        "revenus_potentiels": "5 000 - 50 000€/opération",
        "temps_objectif_5k": "12-24 mois",
        "capital_requis": "30 000 - 150 000€",
        "scalabilite": 3,
        "competences_requises": ["Immobilier", "Négociation"],
        "competences_bonus": ["Gestion de projet", "Artisanat/Manuel"],
        "modele_revenu": "Vente de produits physiques",
        "type_client": "B2C - Particuliers",
        "lieu": ["Sur le terrain/Chez les clients"],
        "visibilite": ["Non - je veux un business anonyme/discret"],
        "risque": 4,
        "passions": ["Immobilier"],
        "avantages": ["Plus-values importantes", "Création de valeur", "Activité variée"],
        "inconvenients": ["Capital très important", "Risque travaux", "Fiscalité"],
        "etapes_demarrage": ["Formation MDB", "Réseau artisans", "Première opération", "Financement"],
        "ressources": ["Formations MDB", "Notaires", "Architectes"]
    },

    # ============================================================
    # SERVICES LOCAUX
    # ============================================================
    "nettoyage_entreprises": {
        "nom": "Entreprise de Nettoyage",
        "categorie": "Services locaux",
        "description": "Nettoyage bureaux et locaux professionnels",
        "revenus_potentiels": "5 000 - 30 000€/mois",
        "temps_objectif_5k": "6-12 mois",
        "capital_requis": "2 000 - 10 000€",
        "scalabilite": 4,
        "competences_requises": ["Organisation/Rigueur"],
        "competences_bonus": ["Leadership/Management", "Vente/Négociation"],
        "modele_revenu": "Prestations de service (freelance, consulting)",
        "type_client": "B2B - Entreprises/Professionnels",
        "lieu": ["Sur le terrain/Chez les clients"],
        "visibilite": ["Modérément - je préfère rester en retrait"],
        "risque": 2,
        "avantages": ["Récurrence garantie", "Scalable", "Peu de concurrence qualité"],
        "inconvenients": ["Gestion personnel", "Horaires décalés", "Marge sur main d'œuvre"],
        "etapes_demarrage": ["Équipement pro", "Premier client", "Équipe", "Contrats récurrents"],
        "ressources": ["Matériel pro", "Logiciel planning"]
    },
    "jardinage_paysagiste": {
        "nom": "Jardinier/Paysagiste",
        "categorie": "Services locaux",
        "description": "Entretien jardins et aménagements paysagers",
        "revenus_potentiels": "3 000 - 15 000€/mois",
        "temps_objectif_5k": "6-12 mois",
        "capital_requis": "3 000 - 15 000€",
        "scalabilite": 3,
        "competences_requises": ["Artisanat/Manuel"],
        "competences_bonus": ["Vente/Négociation"],
        "modele_revenu": "Prestations de service (freelance, consulting)",
        "type_client": "Les deux me conviennent",
        "lieu": ["Sur le terrain/Chez les clients"],
        "visibilite": ["Modérément - je préfère rester en retrait"],
        "risque": 2,
        "avantages": ["Travail extérieur", "Clientèle fidèle", "Crédit d'impôt clients"],
        "inconvenients": ["Saisonnalité", "Physique", "Météo"],
        "etapes_demarrage": ["Équipement", "Agrément services personne", "Clients quartier", "Récurrence"],
        "ressources": ["Matériel jardinage", "CESU"]
    },
    "renovation_bricolage": {
        "nom": "Services de Rénovation/Bricolage",
        "categorie": "Services locaux",
        "description": "Petits travaux et rénovation pour particuliers",
        "revenus_potentiels": "3 000 - 12 000€/mois",
        "temps_objectif_5k": "4-8 mois",
        "capital_requis": "2 000 - 8 000€",
        "scalabilite": 2,
        "competences_requises": ["Artisanat/Manuel"],
        "competences_bonus": ["Vente/Négociation"],
        "modele_revenu": "Prestations de service (freelance, consulting)",
        "type_client": "B2C - Particuliers",
        "lieu": ["Sur le terrain/Chez les clients"],
        "visibilite": ["Modérément - je préfère rester en retrait"],
        "risque": 2,
        "avantages": ["Forte demande", "Tarifs élevés", "Bouche-à-oreille"],
        "inconvenients": ["Physique", "Assurance", "Aléas chantiers"],
        "etapes_demarrage": ["Définir prestations", "Assurance décennale", "Leboncoin/Frizbiz", "Devis clairs"],
        "ressources": ["Frizbiz", "Leboncoin Services"]
    },
    "demenagement": {
        "nom": "Services de Déménagement",
        "categorie": "Services locaux",
        "description": "Déménagements et transports de meubles",
        "revenus_potentiels": "4 000 - 20 000€/mois",
        "temps_objectif_5k": "4-8 mois",
        "capital_requis": "5 000 - 30 000€",
        "scalabilite": 3,
        "competences_requises": ["Organisation/Rigueur"],
        "competences_bonus": ["Leadership/Management"],
        "modele_revenu": "Prestations de service (freelance, consulting)",
        "type_client": "B2C - Particuliers",
        "lieu": ["Sur le terrain/Chez les clients"],
        "visibilite": ["Modérément - je préfère rester en retrait"],
        "risque": 2,
        "avantages": ["Demande constante", "Cash rapide", "Scalable"],
        "inconvenients": ["Physique", "Camion nécessaire", "Assurance"],
        "etapes_demarrage": ["Camion (achat/location)", "Équipe", "Demander devis", "Avis Google"],
        "ressources": ["Déménager Facile", "Leboncoin"]
    },
    "services_seniors": {
        "nom": "Services aux Seniors",
        "categorie": "Services locaux",
        "description": "Aide à domicile, courses, accompagnement",
        "revenus_potentiels": "3 000 - 12 000€/mois",
        "temps_objectif_5k": "6-12 mois",
        "capital_requis": "1 000 - 5 000€",
        "scalabilite": 3,
        "competences_requises": ["Écoute et empathie", "Organisation/Rigueur"],
        "competences_bonus": ["Leadership/Management"],
        "modele_revenu": "Prestations de service (freelance, consulting)",
        "type_client": "B2C - Particuliers",
        "lieu": ["Sur le terrain/Chez les clients"],
        "visibilite": ["Modérément - je préfère rester en retrait"],
        "risque": 1,
        "tendances": ["Services aux seniors"],
        "avantages": ["Marché en croissance", "Impact social", "Financements APA"],
        "inconvenients": ["Émotionnel", "Horaires variables", "Agrément"],
        "etapes_demarrage": ["Agrément SAP", "Services définis", "Partenariats CCAS", "Équipe"],
        "ressources": ["DIRECCTE", "CCAS", "Fédération SAP"]
    },
    "petcare": {
        "nom": "Services Pet Care (garde, promenade)",
        "categorie": "Services locaux",
        "description": "Garde d'animaux, promenades, pet-sitting",
        "revenus_potentiels": "2 000 - 8 000€/mois",
        "temps_objectif_5k": "6-12 mois",
        "capital_requis": "500 - 2 000€",
        "scalabilite": 3,
        "competences_requises": [],
        "competences_bonus": ["Organisation/Rigueur"],
        "modele_revenu": "Prestations de service (freelance, consulting)",
        "type_client": "B2C - Particuliers",
        "lieu": ["Sur le terrain/Chez les clients"],
        "visibilite": ["Modérément - je préfère rester en retrait"],
        "risque": 1,
        "passions": ["Animaux"],
        "avantages": ["Travail avec animaux", "Demande croissante", "Fidélisation"],
        "inconvenients": ["Disponibilité", "Responsabilité", "Vacances scolaires"],
        "etapes_demarrage": ["ACACED si requis", "Rover/Yoopies", "Réseau local", "Services premium"],
        "ressources": ["Rover", "Yoopies", "Animaute"]
    },
    "lavage_auto": {
        "nom": "Lavage Auto à Domicile",
        "categorie": "Services locaux",
        "description": "Nettoyage automobile sur site",
        "revenus_potentiels": "3 000 - 10 000€/mois",
        "temps_objectif_5k": "6-12 mois",
        "capital_requis": "3 000 - 10 000€",
        "scalabilite": 3,
        "competences_requises": ["Organisation/Rigueur"],
        "competences_bonus": [],
        "modele_revenu": "Prestations de service (freelance, consulting)",
        "type_client": "Les deux me conviennent",
        "lieu": ["Sur le terrain/Chez les clients"],
        "visibilite": ["Modérément - je préfère rester en retrait"],
        "risque": 2,
        "passions": ["Automobile"],
        "avantages": ["Service premium", "Récurrence flottes", "Éco-responsable"],
        "inconvenients": ["Équipement", "Météo", "Déplacements"],
        "etapes_demarrage": ["Équipement pro", "Produits écolo", "Cibler entreprises", "Abonnements"],
        "ressources": ["Équipement detailing", "Produits écologiques"]
    },

    # ============================================================
    # FOOD / RESTAURATION
    # ============================================================
    "dark_kitchen": {
        "nom": "Dark Kitchen/Ghost Kitchen",
        "categorie": "Food",
        "description": "Cuisine uniquement pour livraison",
        "revenus_potentiels": "5 000 - 30 000€/mois",
        "temps_objectif_5k": "6-12 mois",
        "capital_requis": "10 000 - 50 000€",
        "scalabilite": 4,
        "competences_requises": ["Cuisine/Restauration"],
        "competences_bonus": ["Marketing digital/SEO/Ads", "Gestion de projet"],
        "modele_revenu": "Vente de produits physiques",
        "type_client": "B2C - Particuliers",
        "lieu": ["Local commercial/Bureau"],
        "visibilite": ["Non - je veux un business anonyme/discret"],
        "risque": 3,
        "passions": ["Food/Restauration"],
        "avantages": ["Pas de salle", "Multi-marques possible", "Scalable"],
        "inconvenients": ["Commissions Uber/Deliveroo", "Dépendance plateformes", "Qualité livraison"],
        "etapes_demarrage": ["Concept différenciant", "Local cuisine", "Uber Eats/Deliveroo", "Marketing visuel"],
        "ressources": ["Uber Eats", "Deliveroo", "Taster"]
    },
    "traiteur": {
        "nom": "Traiteur/Chef à Domicile",
        "categorie": "Food",
        "description": "Services de traiteur événementiel",
        "revenus_potentiels": "4 000 - 20 000€/mois",
        "temps_objectif_5k": "6-12 mois",
        "capital_requis": "3 000 - 15 000€",
        "scalabilite": 3,
        "competences_requises": ["Cuisine/Restauration"],
        "competences_bonus": ["Organisation/Rigueur", "Vente/Négociation"],
        "modele_revenu": "Prestations de service (freelance, consulting)",
        "type_client": "Les deux me conviennent",
        "lieu": ["Sur le terrain/Chez les clients"],
        "visibilite": ["Oui, mais uniquement sur certains canaux"],
        "risque": 2,
        "passions": ["Food/Restauration"],
        "avantages": ["Paniers moyens élevés", "Bouche-à-oreille", "Événements récurrents"],
        "inconvenients": ["Pics d'activité", "Logistique", "Certifications"],
        "etapes_demarrage": ["Agrément sanitaire", "Spécialité culinaire", "Photos portfolio", "Mariages/entreprises"],
        "ressources": ["La Belle Assiette", "Instagram"]
    },
    "food_truck": {
        "nom": "Food Truck",
        "categorie": "Food",
        "description": "Restauration mobile",
        "revenus_potentiels": "4 000 - 15 000€/mois",
        "temps_objectif_5k": "6-12 mois",
        "capital_requis": "20 000 - 80 000€",
        "scalabilite": 2,
        "competences_requises": ["Cuisine/Restauration"],
        "competences_bonus": ["Marketing digital/SEO/Ads"],
        "modele_revenu": "Vente de produits physiques",
        "type_client": "B2C - Particuliers",
        "lieu": ["Sur le terrain/Chez les clients"],
        "visibilite": ["Oui, je veux être le visage de mon business"],
        "risque": 3,
        "passions": ["Food/Restauration"],
        "avantages": ["Mobilité", "Investissement < restaurant", "Événements"],
        "inconvenients": ["Autorisations", "Météo", "Maintenance véhicule"],
        "etapes_demarrage": ["Camion équipé", "Concept fort", "Emplacements", "Instagram local"],
        "ressources": ["Food Truck Agency", "Marchés"]
    },
    "produits_alimentaires": {
        "nom": "Production Alimentaire Artisanale",
        "categorie": "Food",
        "description": "Fabrication et vente de produits (confitures, biscuits...)",
        "revenus_potentiels": "2 000 - 12 000€/mois",
        "temps_objectif_5k": "12-24 mois",
        "capital_requis": "5 000 - 25 000€",
        "scalabilite": 3,
        "competences_requises": ["Cuisine/Restauration"],
        "competences_bonus": ["Marketing digital/SEO/Ads"],
        "modele_revenu": "Vente de produits physiques",
        "type_client": "Les deux me conviennent",
        "lieu": ["Local commercial/Bureau"],
        "visibilite": ["Oui, mais uniquement sur certains canaux"],
        "risque": 2,
        "passions": ["Food/Restauration"],
        "avantages": ["Marges artisanales", "Distribution multi-canal", "Scalable production"],
        "inconvenients": ["Normes sanitaires", "DLC", "Investissement matériel"],
        "etapes_demarrage": ["Agrément sanitaire", "Recettes signature", "Marchés locaux", "E-commerce"],
        "ressources": ["Laboratoire partagé", "Marchés locaux"]
    },

    # ============================================================
    # ÉVÉNEMENTIEL
    # ============================================================
    "wedding_planner": {
        "nom": "Wedding Planner",
        "categorie": "Événementiel",
        "description": "Organisation de mariages",
        "revenus_potentiels": "3 000 - 15 000€/mois (saison)",
        "temps_objectif_5k": "12-18 mois",
        "capital_requis": "1 000 - 5 000€",
        "scalabilite": 2,
        "competences_requises": ["Organisation/Rigueur"],
        "competences_bonus": ["Créativité/Innovation", "Négociation"],
        "modele_revenu": "Prestations de service (freelance, consulting)",
        "type_client": "B2C - Particuliers",
        "lieu": ["Principalement à domicile avec déplacements occasionnels", "Sur le terrain/Chez les clients"],
        "visibilite": ["Oui, je veux être le visage de mon business"],
        "risque": 2,
        "avantages": ["Tarifs élevés", "Travail passion", "Recommandations"],
        "inconvenients": ["Saisonnalité forte", "Stress jour J", "Week-ends"],
        "etapes_demarrage": ["Formation wedding planner", "Portfolio", "Réseau prestataires", "Instagram/Pinterest"],
        "ressources": ["Mariages.net", "Pinterest", "Instagram"]
    },
    "event_entreprise": {
        "nom": "Organisateur d'Événements B2B",
        "categorie": "Événementiel",
        "description": "Organisation séminaires, team buildings, lancements",
        "revenus_potentiels": "5 000 - 30 000€/mois",
        "temps_objectif_5k": "6-12 mois",
        "capital_requis": "2 000 - 10 000€",
        "scalabilite": 3,
        "competences_requises": ["Organisation/Rigueur", "Vente/Négociation"],
        "competences_bonus": ["Créativité/Innovation", "Networking/Création de contacts"],
        "modele_revenu": "Prestations de service (freelance, consulting)",
        "type_client": "B2B - Entreprises/Professionnels",
        "lieu": ["Principalement à domicile avec déplacements occasionnels"],
        "visibilite": ["Oui, je veux être le visage de mon business"],
        "risque": 2,
        "avantages": ["Budgets importants", "Récurrence annuelle", "B2B = paiement sûr"],
        "inconvenients": ["Cycle de vente", "Responsabilité", "Pics d'activité"],
        "etapes_demarrage": ["Niche sectorielle", "Réseau lieux/prestataires", "Prospection RH/COM", "Études de cas"],
        "ressources": ["LinkedIn", "EventMB"]
    },
    "dj_animation": {
        "nom": "DJ/Animateur Événementiel",
        "categorie": "Événementiel",
        "description": "Animation musicale mariages, soirées, événements",
        "revenus_potentiels": "2 000 - 12 000€/mois",
        "temps_objectif_5k": "6-12 mois",
        "capital_requis": "3 000 - 15 000€",
        "scalabilite": 2,
        "competences_requises": ["Communication/Prise de parole"],
        "competences_bonus": ["Créativité/Innovation"],
        "modele_revenu": "Prestations de service (freelance, consulting)",
        "type_client": "Les deux me conviennent",
        "lieu": ["Sur le terrain/Chez les clients"],
        "visibilite": ["Oui, je veux être le visage de mon business"],
        "risque": 2,
        "passions": ["Divertissement/Gaming", "Art/Créativité"],
        "avantages": ["Passion musique", "Cachets week-end", "Bouche-à-oreille"],
        "inconvenients": ["Week-ends occupés", "Saisonnalité", "Matériel à transporter"],
        "etapes_demarrage": ["Matériel DJ", "Mix démo", "Mariages.net", "Réseau lieux"],
        "ressources": ["Mariages.net", "Matériel Pioneer/Denon"]
    },
    "photographe": {
        "nom": "Photographe Professionnel",
        "categorie": "Événementiel",
        "description": "Photos mariages, portraits, événements, corporate",
        "revenus_potentiels": "2 500 - 12 000€/mois",
        "temps_objectif_5k": "6-12 mois",
        "capital_requis": "3 000 - 15 000€",
        "scalabilite": 2,
        "competences_requises": ["Vidéo/Montage"],
        "competences_bonus": ["Marketing digital/SEO/Ads", "Créativité/Innovation"],
        "modele_revenu": "Prestations de service (freelance, consulting)",
        "type_client": "Les deux me conviennent",
        "lieu": ["Sur le terrain/Chez les clients"],
        "visibilite": ["Oui, je veux être le visage de mon business"],
        "risque": 2,
        "passions": ["Art/Créativité"],
        "avantages": ["Travail créatif", "Diversité clients", "Portfolio vendeur"],
        "inconvenients": ["Investissement matériel", "Post-traitement long", "Concurrence"],
        "etapes_demarrage": ["Matériel pro", "Portfolio varié", "Niche (mariage/corporate)", "Instagram"],
        "ressources": ["Instagram", "Mariages.net", "Lightroom"]
    },

    # ============================================================
    # PRODUITS DIGITAUX
    # ============================================================
    "ebooks": {
        "nom": "Auteur d'Ebooks",
        "categorie": "Produits digitaux",
        "description": "Écriture et vente d'ebooks",
        "revenus_potentiels": "500 - 10 000€/mois",
        "temps_objectif_5k": "12-24 mois",
        "capital_requis": "0 - 500€",
        "scalabilite": 5,
        "competences_requises": ["Rédaction/Copywriting"],
        "competences_bonus": ["Marketing digital/SEO/Ads"],
        "modele_revenu": "Vente de produits digitaux (formations, ebooks)",
        "type_client": "B2C - Particuliers",
        "lieu": ["100% à domicile/remote", "Nomade digital - depuis n'importe où"],
        "visibilite": ["Non - je veux un business anonyme/discret", "Oui, mais uniquement sur certains canaux"],
        "risque": 1,
        "avantages": ["Revenus passifs", "Zéro stock", "Expertise monétisée"],
        "inconvenients": ["Concurrence Kindle", "Revenus unitaires faibles", "Marketing nécessaire"],
        "etapes_demarrage": ["Sujet demandé", "Rédaction", "Couverture pro", "Amazon KDP"],
        "ressources": ["Amazon KDP", "Canva", "Gumroad"]
    },
    "communaute_payante": {
        "nom": "Communauté Payante/Membership",
        "categorie": "Produits digitaux",
        "description": "Communauté premium avec contenu exclusif",
        "revenus_potentiels": "2 000 - 30 000€/mois",
        "temps_objectif_5k": "8-18 mois",
        "capital_requis": "0 - 1 000€",
        "scalabilite": 4,
        "competences_requises": ["Pédagogie/Transmission"],
        "competences_bonus": ["Marketing digital/SEO/Ads", "Communication/Prise de parole"],
        "modele_revenu": "Abonnements/Revenus récurrents (SaaS, membership)",
        "type_client": "B2C - Particuliers",
        "lieu": ["100% à domicile/remote"],
        "visibilite": ["Oui, je veux être le visage de mon business"],
        "risque": 2,
        "avantages": ["Revenus récurrents", "Communauté engagée", "Upsell possible"],
        "inconvenients": ["Animation constante", "Churn", "Valeur continue"],
        "etapes_demarrage": ["Audience existante", "Plateforme (Circle, Slack)", "Contenu exclusif", "Lancement"],
        "ressources": ["Circle", "Slack", "Discord", "Patreon"]
    }
}

# Nombre total de modèles
TOTAL_MODELS = len(BUSINESS_MODELS)

# Catégories pour le filtrage
CATEGORIES = {
    "freelance": [k for k, v in BUSINESS_MODELS.items() if v.get("categorie") == "Freelance"],
    "agence": [k for k, v in BUSINESS_MODELS.items() if v.get("categorie") == "Agence"],
    "formation": [k for k, v in BUSINESS_MODELS.items() if v.get("categorie") == "Formation"],
    "ecommerce": [k for k, v in BUSINESS_MODELS.items() if v.get("categorie") == "E-commerce"],
    "tech": [k for k, v in BUSINESS_MODELS.items() if v.get("categorie") == "Tech"],
    "contenu": [k for k, v in BUSINESS_MODELS.items() if v.get("categorie") == "Contenu"],
    "immobilier": [k for k, v in BUSINESS_MODELS.items() if v.get("categorie") == "Immobilier"],
    "services_locaux": [k for k, v in BUSINESS_MODELS.items() if v.get("categorie") == "Services locaux"],
    "food": [k for k, v in BUSINESS_MODELS.items() if v.get("categorie") == "Food"],
    "evenementiel": [k for k, v in BUSINESS_MODELS.items() if v.get("categorie") == "Événementiel"],
    "produits_digitaux": [k for k, v in BUSINESS_MODELS.items() if v.get("categorie") == "Produits digitaux"],
}
